import { StyleSheet } from 'react-native';
import { me } from '../../../../design-system/mint-editorial';

/**
 * StyleSheet for the Expenses screen + its sub-components.
 * Extracted 2026-05-09 (AUDIT_PUNCH_LIST P2 #44a).
 */
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg },
  // Legacy headerSection / headerOverline kept for backwards-compat
  // with any leaf component that imported them; the new layout uses
  // the topNav + screenHeader pair below instead.
  headerSection: {
    backgroundColor: me.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  headerOverline: {
    fontSize: 10,
    fontWeight: '700',
    color: me.ink3,
    letterSpacing: 1.2,
    textAlign: 'center',
    paddingTop: 8,
  },
  topNav: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenHeader: {
    paddingHorizontal: 20,
    marginTop: 6,
    marginBottom: 20,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  headline: {
    fontFamily: me.font.display,
    fontSize: 32,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  sub: {
    fontSize: 14,
    color: me.ink3,
    marginTop: 4,
  },
  recentEyebrow: {
    paddingHorizontal: 4,
    marginTop: 10,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: me.surface,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: me.line,
  },
  statIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  statLabel: {
    fontSize: 10,
    color: me.ink3,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '800',
    color: me.ink,
    marginBottom: 2,
  },
  filterScrollView: { flexGrow: 0 },
  filterRow: { paddingHorizontal: 16, paddingVertical: 10, gap: 8 },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
  },
  filterChipActive: { backgroundColor: me.ink },
  filterChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink2,
  },
  filterChipTextActive: { color: me.onBrand },
  formCard: { marginHorizontal: 16, marginBottom: 12 },
  jobScopeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: me.bg2,
    borderRadius: 8,
    marginBottom: 8,
  },
  jobScopeBannerText: {
    fontSize: 13,
    color: me.ink2,
    flex: 1,
  },
  input: {
    backgroundColor: me.bg2,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: me.ink,
    marginBottom: 8,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: me.ink2,
    marginBottom: 8,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  formCategoryRow: { gap: 8, paddingBottom: 10 },
  formCategoryChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: me.bg2,
    borderWidth: 1,
    borderColor: me.line,
  },
  formCategoryChipActive: {
    backgroundColor: me.ink,
    borderColor: me.ink,
  },
  formCategoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: me.ink2,
  },
  formCategoryTextActive: { color: me.onBrand },
  billableToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: me.bg2,
    marginBottom: 10,
  },
  billableCopy: { flex: 1 },
  billableTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: me.ink,
  },
  billableHint: {
    fontSize: 12,
    color: me.ink2,
    marginTop: 2,
  },
  formActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  list: { paddingHorizontal: 16, paddingBottom: 80 },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: me.surface,
    borderRadius: 20,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: me.line,
  },
  categoryDot: { width: 10, height: 10, borderRadius: 5, marginRight: 12 },
  expenseInfo: { flex: 1 },
  expenseDesc: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
  },
  expenseDate: { fontSize: 12, color: me.ink3, marginTop: 2 },
  expenseRight: { alignItems: 'flex-end', gap: 4 },
  expenseAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: me.ink,
  },
  deleteButton: { marginLeft: 8, padding: 4 },
  emptyWrap: { alignItems: 'center', paddingTop: 48, paddingHorizontal: 32 },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: me.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 14,
    color: me.ink2,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  emptyCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: me.brand,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 24,
  },
  emptyCtaText: {
    fontSize: 15,
    fontWeight: '700',
    color: me.onBrand,
  },
  snackbar: {
    position: 'absolute',
    bottom: 90,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: me.ink,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    ...me.shadow.pop,
  },
  snackbarText: {
    fontSize: 14,
    color: me.onBrand,
    flex: 1,
    marginRight: 12,
  },
  snackbarUndo: { fontSize: 14, fontWeight: '700', color: '#3B82F6' },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: me.brand,
    justifyContent: 'center',
    alignItems: 'center',
    ...me.shadow.pop,
  },
});
