import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg },
  header: {
    backgroundColor: me.surface,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  headerCenter: { flex: 1, paddingTop: 4 },
  headerTitle: {
    fontFamily: me.font.display,
    fontSize: 26,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  headerSubtitle: {
    fontSize: 13,
    color: me.ink2,
    marginTop: 4,
    lineHeight: 18,
  },
  scroll: { flex: 1 },

  // Line items
  itemsCard: {
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
  },
  sectionEyebrow: {
    fontSize: 11,
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    fontWeight: '700',
    marginBottom: 10,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  itemRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line2,
  },
  itemLabel: { flex: 1, fontSize: 14, color: me.ink, paddingVertical: 4 },
  itemAmountWrap: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
  itemAmountPrefix: {
    fontFamily: me.font.display,
    fontSize: 17,
    color: me.ink3,
  },
  itemAmount: {
    fontFamily: me.font.display,
    fontSize: 17,
    color: me.ink,
    minWidth: 56,
    textAlign: 'right',
  },
  removeBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtn: {
    width: '100%',
    paddingVertical: 10,
    marginTop: 8,
    borderRadius: 12,
    backgroundColor: me.bg2,
    alignItems: 'center',
  },
  addBtnText: { color: me.brand, fontSize: 13, fontWeight: '600' },

  // Totals
  totalsRow: { flexDirection: 'row', gap: 8, marginBottom: 18 },
  totalCard: {
    flex: 1,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
    borderRadius: 14,
    padding: 12,
  },
  totalCardDark: { backgroundColor: me.ink, borderColor: me.ink },
  totalLabel: { fontSize: 11, color: me.ink3 },
  totalLabelDark: { color: 'rgba(236,244,238,0.6)' },
  totalValue: {
    fontFamily: me.font.display,
    fontSize: 22,
    color: me.ink,
    letterSpacing: me.displayTracking,
    marginTop: 2,
  },
  totalValueDark: { color: me.onBrand },

  // Customer
  customerInput: {
    width: '100%',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: me.line,
    backgroundColor: me.surface,
    fontSize: 14,
    color: me.ink,
  },
  customerHint: { fontSize: 12, color: me.ink3, marginTop: 8 },

  // Footer
  footer: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: me.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
    ...me.shadow.pop,
  },
  btnSecondary: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSecondaryText: { color: me.ink, fontSize: 14, fontWeight: '600' },
  btnPrimary: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: me.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnPrimaryText: { color: me.onBrand, fontSize: 14, fontWeight: '600' },
  btnDisabled: { opacity: 0.5 },
  btnDisabledText: { color: me.ink3 },
});
