/**
 * data.yaml generator for YOLO training
 */

/**
 * Generate data.yaml content for YOLO training
 */
export function generateDataYaml(config: {
  path: string;
  train: string;
  val: string;
  test: string;
  nc: number;
  names: string[];
}): string {
  const namesYaml = config.names.map((name, i) => `  ${i}: ${name}`).join('\n');

  return `# YOLO Training Dataset Configuration
# Generated by YOLOTrainingDataEnhanced
# Path to dataset root
path: ${config.path}

# Train/val/test paths relative to path
train: train/images
val: val/images
test: test/images

# Number of classes
nc: ${config.nc}

# Class names
names:
${namesYaml}

# Dataset info
roboflow:
  workspace: mintenance
  project: building-defect-detection
  version: continuous-learning
  license: Private
  url: https://mintenance.com
`;
}
