#!/usr/bin/env ts-node

/**
 * Fix Any Types Script
 * Identifies and suggests proper types to replace 'any' usage
 * Improves type safety and reduces runtime errors
 */

import * as fs from 'fs';
import * as path from 'path';
import * as glob from 'glob';

interface TypeSuggestion {
  file: string;
  line: number;
  original: string;
  suggestion: string;
  context: string;
}

const suggestions: TypeSuggestion[] = [];

// Common patterns and their type suggestions
const typePatterns = [
  { pattern: /:\s*any\[\]/, suggestion: ': unknown[]', context: 'array' },
  { pattern: /:\s*any\s*=\s*{/, suggestion: ': Record<string, unknown>', context: 'object' },
  { pattern: /\(([^)]*:\s*any[^)]*)\)/, suggestion: 'unknown', context: 'parameter' },
  { pattern: /:\s*any\s*;/, suggestion: ': unknown;', context: 'property' },
  { pattern: /as\s+any/, suggestion: 'as unknown', context: 'type assertion' },
  { pattern: /<any>/, suggestion: '<unknown>', context: 'generic' }
];

// Context-specific type suggestions
const contextualTypes: Record<string, string> = {
  'error': 'Error | unknown',
  'response': 'Response',
  'request': 'Request',
  'event': 'Event',
  'data': 'unknown',
  'result': 'unknown',
  'payload': 'Record<string, unknown>',
  'config': 'Record<string, unknown>',
  'options': 'Record<string, unknown>',
  'params': 'Record<string, unknown>',
  'props': 'Record<string, unknown>',
  'state': 'Record<string, unknown>',
  'context': 'Record<string, unknown>',
  'user': '{ id: string; email: string; [key: string]: unknown }',
  'job': '{ id: string; [key: string]: unknown }',
  'bid': '{ id: string; amount: number; [key: string]: unknown }',
};

// Files with 'any' types (from grep results)
const filesToProcess = glob.sync('apps/web/**/*.{ts,tsx}', {
  ignore: [
    '**/node_modules/**',
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.spec.ts',
    '**/*.spec.tsx',
    '**/dist/**',
    '**/.next/**'
  ]
});

console.log('🔍 Analyzing files for "any" type usage...\n');

let totalAnyTypes = 0;
let filesWithAny = 0;

filesToProcess.forEach(filePath => {
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  let fileHasAny = false;
  let anyCount = 0;

  lines.forEach((line, index) => {
    // Skip comments and strings
    if (line.trim().startsWith('//') || line.trim().startsWith('*')) {
      return;
    }

    // Check for 'any' type usage
    const anyMatches = line.match(/:\s*any\b|as\s+any\b|<any>/g);

    if (anyMatches) {
      fileHasAny = true;
      anyCount += anyMatches.length;

      // Try to determine context for better suggestions
      const variableName = line.match(/(\w+)\s*:\s*any/)?.[1]?.toLowerCase() || '';
      let suggestedType = 'unknown';

      // Check for contextual type
      for (const [key, type] of Object.entries(contextualTypes)) {
        if (variableName.includes(key)) {
          suggestedType = type;
          break;
        }
      }

      // Check for specific patterns
      if (line.includes('any[]')) {
        suggestedType = 'unknown[]';
      } else if (line.includes('any | null')) {
        suggestedType = 'unknown | null';
      } else if (line.includes('any | undefined')) {
        suggestedType = 'unknown | undefined';
      } else if (line.includes('Promise<any>')) {
        suggestedType = 'Promise<unknown>';
      } else if (line.includes('Record<string, any>')) {
        suggestedType = 'Record<string, unknown>';
      }

      suggestions.push({
        file: filePath,
        line: index + 1,
        original: line.trim(),
        suggestion: line.replace(/:\s*any\b/g, `: ${suggestedType}`)
          .replace(/as\s+any\b/g, `as ${suggestedType}`)
          .replace(/<any>/g, `<${suggestedType}>`)
          .trim(),
        context: variableName || 'general'
      });
    }
  });

  if (fileHasAny) {
    filesWithAny++;
    totalAnyTypes += anyCount;
    console.log(`  ⚠️  ${path.relative(process.cwd(), filePath)}: ${anyCount} 'any' types found`);
  }
});

console.log(`\n📊 Summary: Found ${totalAnyTypes} 'any' types in ${filesWithAny} files\n`);

// Generate type definition file for common types
const typeDefinitions = `
/**
 * Common type definitions to replace 'any' usage
 * Generated by fix-any-types script
 */

// API Response types
export interface ApiResponse<T = unknown> {
  data?: T;
  error?: string;
  message?: string;
  success: boolean;
}

// User types
export interface User {
  id: string;
  email: string;
  name?: string;
  role: 'homeowner' | 'contractor' | 'admin';
  created_at: string;
  [key: string]: unknown;
}

// Job types
export interface Job {
  id: string;
  title: string;
  description: string;
  user_id: string;
  status: string;
  created_at: string;
  [key: string]: unknown;
}

// Bid types
export interface Bid {
  id: string;
  job_id: string;
  contractor_id: string;
  amount: number;
  status: string;
  created_at: string;
  [key: string]: unknown;
}

// Form data types
export type FormData = Record<string, string | number | boolean | File | null>;

// Event handler types
export type EventHandler<T = unknown> = (event: T) => void | Promise<void>;

// Generic function types
export type AsyncFunction<T = unknown, R = unknown> = (arg: T) => Promise<R>;
export type SyncFunction<T = unknown, R = unknown> = (arg: T) => R;

// Utility types
export type Nullable<T> = T | null;
export type Optional<T> = T | undefined;
export type Maybe<T> = T | null | undefined;

// Replace 'any' with these types:
export type SafeAny = unknown;
export type AnyObject = Record<string, unknown>;
export type AnyArray = unknown[];
export type AnyFunction = (...args: unknown[]) => unknown;
`;

// Write type definitions
fs.writeFileSync('apps/web/lib/types/safe-types.ts', typeDefinitions);
console.log('✅ Created type definitions file: apps/web/lib/types/safe-types.ts\n');

// Generate migration guide
console.log('📝 Migration Guide:\n');
console.log('1. Import the new types:');
console.log("   import type { SafeAny, AnyObject, User, Job, Bid } from '@/lib/types/safe-types';");
console.log('\n2. Common replacements:');
console.log('   - any           → unknown');
console.log('   - any[]         → unknown[]');
console.log('   - any | null    → unknown | null');
console.log('   - Promise<any>  → Promise<unknown>');
console.log('   - (e: unknown)      → (e: unknown) or (e: Error)');
console.log('   - data: any     → data: unknown');
console.log('\n3. For objects with known structure, define interfaces:');
console.log('   - config: any   → config: ConfigInterface');
console.log('   - user: any     → user: User');
console.log('   - response: any → response: ApiResponse<T>');
console.log('\n4. Use type assertions when necessary:');
console.log('   const data = response as ApiResponse<User>;');
console.log('\n5. Add runtime type checking for external data:');
console.log('   if (isUser(data)) { /* safely use as User */ }');

// Generate ESLint configuration
const eslintRule = {
  rules: {
    '@typescript-eslint/no-explicit-any': 'error',
    '@typescript-eslint/no-unsafe-assignment': 'warn',
    '@typescript-eslint/no-unsafe-member-access': 'warn',
    '@typescript-eslint/no-unsafe-call': 'warn',
    '@typescript-eslint/no-unsafe-return': 'warn',
  }
};

console.log('\n💡 Add to .eslintrc.json to prevent future "any" usage:');
console.log(JSON.stringify(eslintRule, null, 2));

// Write suggestions to file for review
const suggestionsFile = suggestions.map(s =>
  `${s.file}:${s.line}\nOriginal: ${s.original}\nSuggested: ${s.suggestion}\n`
).join('\n---\n');

fs.writeFileSync('any-type-suggestions.txt', suggestionsFile);
console.log('\n📄 Detailed suggestions saved to: any-type-suggestions.txt');