/**
 * AISearchScreen + sub-component styles — Mint Editorial.
 * Paper background, serif inline header, hex-free palette.
 */
import { StyleSheet } from 'react-native';
import { me } from '../../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: me.bg,
  },
  // Top nav + serif inline header — replaces legacy ScreenHeader.
  topNav: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenHeader: {
    paddingHorizontal: 20,
    marginTop: 6,
    marginBottom: 14,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  headline: {
    fontFamily: me.font.display,
    fontSize: 32,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  sub: {
    fontSize: 14,
    color: me.ink3,
    marginTop: 4,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 10,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: me.surface,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: me.line2,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: me.ink,
    marginLeft: 8,
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: me.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: me.line2,
  },
  filterButtonActive: {
    backgroundColor: me.brand,
    borderColor: me.brand,
  },
  filtersContainer: {
    backgroundColor: me.surface,
    marginHorizontal: 20,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: me.line2,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  filterLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: me.ink,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  filterValue: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: me.bg2,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    gap: 6,
  },
  filterValueText: {
    fontSize: 12,
    fontWeight: '600',
    color: me.ink2,
  },
  clearFiltersButton: {
    alignSelf: 'flex-end',
    paddingVertical: 6,
  },
  clearFiltersText: {
    fontSize: 12,
    color: me.brand,
    fontWeight: '700',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 13,
    color: me.ink2,
    marginTop: 12,
  },
  suggestionsContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  suggestionsTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 10,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line2,
    gap: 12,
  },
  suggestionIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: me.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionText: {
    flex: 1,
    fontSize: 15,
    color: me.ink,
  },
  resultsContainer: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  resultItem: {
    backgroundColor: me.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    borderWidth: 1,
    borderColor: me.line2,
    ...me.shadow.card,
  },
  resultIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultDetails: {
    flex: 1,
  },
  resultTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 4,
  },
  resultDescription: {
    fontSize: 13,
    color: me.ink2,
    marginBottom: 8,
    lineHeight: 18,
  },
  resultMetadata: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metadataItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metadataText: {
    fontSize: 11,
    color: me.ink3,
    fontWeight: '600',
  },
  relevanceScore: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
    height: 38,
    backgroundColor: me.infoBg,
    borderRadius: 12,
  },
  scoreText: {
    fontSize: 11,
    fontWeight: '700',
    color: me.infoFg,
  },
  emptyContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  emptyTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 14,
  },
  trendingContainer: {
    paddingBottom: 24,
    gap: 10,
  },
  trendingItem: {
    flex: 1,
    backgroundColor: me.surface,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    margin: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: me.line2,
    ...me.shadow.card,
  },
  trendingText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink,
    textAlign: 'center',
  },
  noResultsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  noResultsIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line2,
    ...me.shadow.card,
  },
  noResultsTitle: {
    fontFamily: me.font.display,
    fontSize: 22,
    color: me.ink,
    marginBottom: 6,
    letterSpacing: me.displayTracking,
  },
  noResultsSubtitle: {
    fontSize: 13,
    color: me.ink2,
    textAlign: 'center',
    lineHeight: 19,
  },
});
