import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg2 },
  scrollView: { flex: 1 },
  content: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: me.surface,
    borderRadius: 16,
    marginBottom: 16,
    overflow: 'hidden',
    ...me.shadow.card,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    paddingBottom: 8,
  },
  iconChip: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { fontSize: 16, fontWeight: '600', color: me.ink },
  bodyText: {
    fontSize: 13,
    color: me.ink2,
    lineHeight: 20,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  catRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  catBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  catLabel: {
    fontSize: 14,
    color: me.ink,
    fontWeight: '400',
  },
  exportRow: { flexDirection: 'row', alignItems: 'center', padding: 14 },
  exportDate: {
    fontSize: 14,
    fontWeight: '500',
    color: me.ink,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 3,
  },
  statusText: { fontSize: 12, fontWeight: '500' },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: me.ink,
    borderRadius: 12,
    paddingVertical: 15,
    marginTop: 8,
    marginBottom: 12,
  },
  buttonDisabled: { backgroundColor: me.ink3 },
  buttonText: {
    fontSize: 15,
    fontWeight: '600',
    color: me.onBrand,
  },
  footnote: {
    fontSize: 12,
    color: me.ink3,
    lineHeight: 18,
    paddingHorizontal: 4,
    textAlign: 'center',
  },
});
