import { StyleSheet, Platform } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: me.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
  },
  handle: {
    width: 36,
    height: 4,
    backgroundColor: me.line,
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 16,
  },
  iconBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: me.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: me.ink,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: me.ink2,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: me.ink2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: me.line,
    borderRadius: me.radius.input,
    backgroundColor: me.bg2,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: me.ink,
  },
  codeInput: {
    fontSize: 24,
    letterSpacing: 8,
    textAlign: 'center',
    fontWeight: '700',
  },
  hint: {
    fontSize: 12,
    color: me.ink3,
    marginTop: 6,
    marginBottom: 16,
  },
  errorBox: {
    backgroundColor: me.errBg,
    borderRadius: me.radius.input,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  errorText: {
    fontSize: 13,
    color: me.errFg,
    lineHeight: 18,
  },
  primaryButton: {
    backgroundColor: me.brand,
    borderRadius: 28,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  primaryButtonDisabled: {
    backgroundColor: me.line,
  },
  primaryButtonText: {
    color: me.onBrand,
    fontSize: 15,
    fontWeight: '600',
  },
  secondaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  linkText: {
    fontSize: 14,
    fontWeight: '600',
    color: me.brand,
  },
  linkTextDisabled: {
    color: me.ink3,
  },
  dismissText: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink2,
    textAlign: 'center',
    marginTop: 16,
    textDecorationLine: 'underline',
  },
});
