/**
 * Lazy-loaded wrapper for Advanced Search Service
 * Generated by bundle optimization script
 */

import React, { Suspense } from 'react';
import { createLazyComponent } from '../../utils/codeSplitting';
import { LoadingSpinner } from '../LoadingSpinner';

const LazyAdvancedSearchService = createLazyComponent(
  (() => import('../../services/AdvancedSearchService')) as unknown as () => Promise<{ default: React.ComponentType<Record<string, unknown>> }>,
  {
    chunkName: 'advanced-search-service',
    timeout: 10000,
    retryAttempts: 3,
    preload: true,
  }
);

export const AdvancedSearchService = (props: Record<string, unknown>) => (
  <Suspense fallback={<LoadingSpinner />}>
    <LazyAdvancedSearchService {...props} />
  </Suspense>
);

export default AdvancedSearchService;
