/**
 * Lazy-loaded wrapper for Business Dashboard
 * Generated by bundle optimization script
 */

import React, { Suspense } from 'react';
import { createLazyComponent } from '../../utils/codeSplitting';
import { LoadingSpinner } from '../LoadingSpinner';

const LazyBusinessDashboard = createLazyComponent(
  () => import('../components/analytics/BusinessDashboardx'),
  {
    chunkName: 'business-dashboard',
    timeout: 10000,
    retryAttempts: 3,
    preload: true,
  }
);

export const BusinessDashboard = (props: any) => (
  <Suspense fallback={<LoadingSpinner />}>
    <LazyBusinessDashboard {...props} />
  </Suspense>
);

export default BusinessDashboard;
