/**
 * Lazy-loaded components index
 * Generated by bundle optimization script
 */

export { MLTrainingPipeline } from './MLTrainingPipeline';
export { AdvancedMLService } from './AdvancedMLService';
export { VideoCallService } from './VideoCallService';
export { BusinessDashboard } from './BusinessDashboard';
export { AdvancedSearchService } from './AdvancedSearchService';
