/**
 * Lazy-loaded components index
 * Generated by bundle optimization script
 */

export { VideoCallService } from './VideoCallService';
export { BusinessDashboard } from './BusinessDashboard';
export { AdvancedSearchService } from './AdvancedSearchService';
