import { StyleSheet, Platform } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: me.bg2,
  },
  permissionText: {
    fontSize: 17,
    marginTop: 16,
    marginBottom: 24,
    color: me.ink,
  },
  permissionButton: {
    paddingHorizontal: 24,
    paddingVertical: 14,
    backgroundColor: me.ink,
    borderRadius: 28,
  },
  permissionButtonText: {
    color: me.onBrand,
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    zIndex: 10,
  },
  closeButton: {
    padding: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 20,
  },
  helpButton: {
    padding: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 20,
  },
  timerContainer: {
    alignItems: 'center',
  },
  recordingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  recordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  timerText: {
    color: me.onBrand,
    fontSize: 15,
    fontWeight: '600',
  },
  guidanceOverlay: {
    position: 'absolute',
    top: 100,
    left: 16,
    right: 16,
    zIndex: 5,
  },
  guidanceCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  guidanceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  phaseTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: me.ink,
  },
  phaseTimer: {
    fontSize: 13,
    color: me.ink2,
  },
  progressBar: {
    height: 4,
    backgroundColor: me.line,
    borderRadius: 2,
    marginBottom: 16,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: me.brand,
  },
  instructionsList: {
    marginBottom: 12,
  },
  instructionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  instructionText: {
    marginLeft: 8,
    fontSize: 13,
    color: me.ink2,
    flex: 1,
  },
  tipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: me.warnBg,
    padding: 12,
    borderRadius: 12,
  },
  tipText: {
    marginLeft: 8,
    fontSize: 13,
    color: me.accent,
    flex: 1,
  },
  phaseIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  phaseIndicator: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 2,
  },
  phaseIndicatorActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
  },
  phaseIndicatorComplete: {
    backgroundColor: me.brand,
  },
  controls: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  recordButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: me.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 6,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  recordButtonInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.errFg,
  },
  recordButtonStop: {
    borderRadius: 8,
    width: 32,
    height: 32,
  },
  secondaryButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewContainer: {
    flex: 1,
    backgroundColor: me.bg2,
  },
  previewHeader: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: me.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  previewTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: me.ink,
    textAlign: 'center',
  },
  videoPreviewContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  videoPlaceholder: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: me.line,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoInfo: {
    marginTop: 8,
    fontSize: 13,
    color: me.ink2,
  },
  previewActions: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: me.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 28,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  retakeButton: {
    backgroundColor: me.bg2,
  },
  confirmButton: {
    backgroundColor: me.ink,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: me.ink2,
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: me.onBrand,
  },
  uploadProgress: {
    marginLeft: 8,
    fontSize: 13,
    color: me.onBrand,
  },
});
