-- ==========================================================
-- AB ALERTS TABLE MIGRATION
-- Creates table for storing A/B testing alerts
-- ==========================================================

BEGIN;

-- Create ab_alerts table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.ab_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    experiment_id TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    threshold NUMERIC,
    actual_value NUMERIC,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    is_resolved BOOLEAN DEFAULT FALSE
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_ab_alerts_experiment_id ON public.ab_alerts(experiment_id);
CREATE INDEX IF NOT EXISTS idx_ab_alerts_type ON public.ab_alerts(type);
CREATE INDEX IF NOT EXISTS idx_ab_alerts_severity ON public.ab_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_ab_alerts_created_at ON public.ab_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ab_alerts_is_resolved ON public.ab_alerts(is_resolved);

-- Create index for filtering unresolved alerts
CREATE INDEX IF NOT EXISTS idx_ab_alerts_unresolved ON public.ab_alerts(experiment_id, is_resolved) 
WHERE is_resolved = FALSE;

-- Add comment for documentation
COMMENT ON TABLE public.ab_alerts IS 'Stores alerts generated by A/B testing experiments';
COMMENT ON COLUMN public.ab_alerts.experiment_id IS 'Identifier for the A/B test experiment';
COMMENT ON COLUMN public.ab_alerts.severity IS 'Alert severity level: low, medium, high, critical';
COMMENT ON COLUMN public.ab_alerts.type IS 'Type of alert (e.g., conversion_rate, error_rate)';
COMMENT ON COLUMN public.ab_alerts.metadata IS 'Additional alert metadata in JSON format';

-- Enable Row Level Security (RLS)
ALTER TABLE public.ab_alerts ENABLE ROW LEVEL SECURITY;

-- Create policy: Only admins can view all alerts
CREATE POLICY "Admins can view all alerts"
    ON public.ab_alerts
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid()
            AND users.role = 'admin'
        )
    );

-- Create policy: System can insert alerts (via service role)
CREATE POLICY "System can insert alerts"
    ON public.ab_alerts
    FOR INSERT
    WITH CHECK (true);

-- Create policy: Admins can update alerts
CREATE POLICY "Admins can update alerts"
    ON public.ab_alerts
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid()
            AND users.role = 'admin'
        )
    );

COMMIT;

