import { StyleSheet } from 'react-native';
import { me } from '../../../design-system/mint-editorial';
export const styles = StyleSheet.create({
  container: {
    backgroundColor: me.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    ...me.shadow.card,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  form: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: me.bg2,
    borderRadius: 12,
  },
  input: {
    backgroundColor: me.surface,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: me.ink,
    marginBottom: 10,
  },
  freqRow: { flexDirection: 'row', gap: 6, marginBottom: 10 },
  freqChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: me.bg2,
  },
  freqText: {
    fontSize: 12,
    fontWeight: '600',
    color: me.ink2,
  },
  freqTextActive: { color: me.onBrand },
  createBtn: {
    backgroundColor: me.brand,
    borderRadius: 20,
    paddingVertical: 10,
    alignItems: 'center',
  },
  createBtnText: { color: me.onBrand, fontSize: 14, fontWeight: '600' },
  emptyWrap: { alignItems: 'center', paddingVertical: 16, gap: 8 },
  emptyText: { fontSize: 14, color: me.ink3 },
  scheduleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  scheduleInactive: { opacity: 0.5 },
  toggleBtn: { marginRight: 10 },
  scheduleInfo: { flex: 1 },
  scheduleTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
  },
  textInactive: { textDecorationLine: 'line-through' },
  scheduleMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  freqBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  freqBadgeText: { fontSize: 11, fontWeight: '600' },
  dueDate: { fontSize: 12, color: me.ink3 },
});
