import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg },
  header: {
    backgroundColor: me.surface,
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  headerCenter: { flex: 1, paddingTop: 4 },
  headerTitle: {
    fontFamily: me.font.display,
    fontSize: 26,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  headerSubtitle: {
    fontSize: 13,
    color: me.ink2,
    marginTop: 4,
    lineHeight: 18,
  },
  scroll: { flex: 1 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 },
  errorText: { color: me.ink2, fontSize: 14 },
  errorRetry: {
    color: me.brand,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 4,
  },

  // Progress card
  progressCard: {
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
    borderRadius: 18,
    padding: 18,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  // Native RN can't do a conic-gradient ring; approximate with a thick
  // brand border + inner surface circle that shows the %.
  progressRing: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressRingInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressPct: {
    fontFamily: me.font.display,
    fontSize: 22,
    color: me.brand,
    letterSpacing: me.displayTracking,
  },
  progressPctUnit: { fontSize: 12, opacity: 0.6 },
  progressContent: { flex: 1 },
  progressTitle: {
    fontFamily: me.font.display,
    fontSize: 20,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  progressBody: {
    fontSize: 12,
    color: me.ink3,
    marginTop: 4,
    marginBottom: 8,
    lineHeight: 16,
  },
  progressCta: { fontSize: 11, color: me.brand, fontWeight: '600' },

  // Credential rows
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line2,
  },
  rowFirst: { borderTopWidth: 0 },
  rowPressed: { opacity: 0.7 },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 9,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowContent: { flex: 1 },
  rowTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: me.ink,
  },
  rowSubtitle: {
    fontSize: 11,
    color: me.ink3,
    marginTop: 2,
    lineHeight: 14,
  },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 9999,
  },
  pillWarn: { backgroundColor: me.warnBg },
  pillWarnText: { fontSize: 11, fontWeight: '600', color: me.warnFg },
  pillInfo: { backgroundColor: me.infoBg },
  pillInfoText: { fontSize: 11, fontWeight: '600', color: me.infoFg },
  pillError: { backgroundColor: me.errBg },
  pillErrorText: { fontSize: 11, fontWeight: '600', color: me.errFg },
  todoLink: { fontSize: 11, fontWeight: '600', color: me.brand },
});
