import { StyleSheet } from 'react-native';
import { me } from '../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg2 },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: me.ink2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: me.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: { flex: 1, alignItems: 'center', marginHorizontal: 12 },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
  },
  headerSubtitle: {
    fontSize: 13,
    color: me.ink2,
    marginTop: 2,
  },
  bidCountChip: {
    backgroundColor: me.bg2,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bidCountText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink2,
  },
  swiperContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  bidCard: {
    flex: 1,
    backgroundColor: me.surface,
    borderRadius: 20,
    // padding removed so the hero can extend to the card edges; the
    // body block below the hero re-introduces horizontal padding.
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: me.line,
  },
  cardScroll: { flex: 1 },
  contractorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  avatar: { width: 64, height: 64, borderRadius: 32, marginRight: 14 },
  avatarPlaceholder: {
    backgroundColor: me.bg2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contractorInfo: { flex: 1 },
  contractorName: {
    fontSize: 20,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 2,
  },
  companyName: {
    fontSize: 14,
    color: me.ink2,
    marginBottom: 4,
  },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stars: { flexDirection: 'row' },
  ratingText: { fontSize: 13, color: me.ink2 },
  newBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: me.brandSoft,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  newBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: me.brand,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 4,
  },
  locationText: { fontSize: 13, color: me.ink3 },
  viewProfileLink: {
    fontSize: 13,
    fontWeight: '600',
    color: me.brand,
    marginTop: 6,
  },
  bioText: {
    fontSize: 14,
    color: me.ink2,
    lineHeight: 20,
    marginBottom: 16,
    fontStyle: 'italic',
  },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  statChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: me.bg2,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink2,
  },
  amountSection: {
    backgroundColor: me.bg2,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    marginBottom: 16,
  },
  // Quote breakdown (line items)
  quoteBreakdown: {
    backgroundColor: me.bg2,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  quoteBreakdownTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  lineItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  lineItemInfo: { flex: 1, marginRight: 12 },
  lineItemDesc: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink,
  },
  lineItemQty: { fontSize: 12, color: me.ink3, marginTop: 2 },
  lineItemTotal: {
    fontSize: 14,
    fontWeight: '700',
    color: me.ink,
  },
  quoteSummary: { marginTop: 10 },
  quoteSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  quoteSummaryLabel: { fontSize: 13, color: me.ink2 },
  quoteSummaryValue: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink,
  },
  quoteTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: me.line,
    marginTop: 4,
  },
  quoteTotalLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: me.ink,
  },
  quoteTotalValue: {
    fontSize: 15,
    fontWeight: '800',
    color: me.brand,
  },
  amountLabel: {
    fontSize: 13,
    color: me.ink2,
    marginBottom: 4,
  },
  amountValue: {
    fontSize: 32,
    fontWeight: '700',
    color: me.ink,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  detailIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailText: { fontSize: 15, color: me.ink2 },
  proposalSection: {
    marginTop: 12,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
  },
  proposalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
    marginBottom: 8,
  },
  proposalText: {
    fontSize: 15,
    color: me.ink2,
    lineHeight: 22,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 40,
    paddingVertical: 16,
    paddingBottom: 24,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
    backgroundColor: me.surface,
  },
  rejectButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
    ...me.shadow.card,
  },
  acceptButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.brandSoft,
    justifyContent: 'center',
    alignItems: 'center',
    ...me.shadow.card,
  },
  overlayPass: { alignItems: 'center' },
  overlayPassText: {
    fontSize: 24,
    fontWeight: '700',
    color: me.errFg,
  },
  overlayAccept: { alignItems: 'center' },
  overlayAcceptText: {
    fontSize: 24,
    fontWeight: '700',
    color: me.brand,
  },
  emptyIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: me.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: me.ink,
  },
  emptySubtitle: {
    fontSize: 15,
    color: me.ink2,
    textAlign: 'center',
    marginTop: 8,
  },
  goBackButton: {
    marginTop: 24,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: me.ink,
  },
  goBackButtonText: {
    color: me.onBrand,
    fontSize: 16,
    fontWeight: '600',
  },
  processingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  celebrationOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  celebrationCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: me.brand,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Undo snackbar (step 4d). Sits above the action buttons so the
  // user's thumb is naturally near the UNDO target.
  undoSnackbar: {
    position: 'absolute',
    bottom: 96,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: me.ink,
    borderRadius: 14,
    zIndex: 50,
  },
  undoSnackbarText: {
    flex: 1,
    fontSize: 14,
    color: me.onBrand,
    fontWeight: '500',
  },
  undoSnackbarAction: {
    fontSize: 14,
    fontWeight: '700',
    color: me.accent,
    marginLeft: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: me.surface,
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: me.line,
  },
  summaryItem: { alignItems: 'center' },
  summaryIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 11,
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 2,
  },
  sortRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  sortChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
  },
  sortChipActive: {
    backgroundColor: me.brand,
    borderColor: me.brand,
  },
  sortChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink2,
  },
  sortChipTextActive: { color: me.onBrand },

  // Media-first hero (BidReviewCard #1 step 2): blurred avatar bg or
  // teal gradient, with crisp 96x96 avatar overlapping the body.
  hero: {
    width: '100%',
    height: 140,
    justifyContent: 'flex-end',
    backgroundColor: me.brand,
  },
  heroImage: { resizeMode: 'cover' },
  heroDimOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  heroAvatarWrap: {
    alignSelf: 'center',
    marginTop: -48,
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: me.surface,
    padding: 4,
    ...me.shadow.pop,
  },
  heroAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
  },
  body: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
    alignItems: 'stretch',
  },
  heroName: {
    fontSize: 22,
    fontWeight: '700',
    color: me.ink,
    textAlign: 'center',
    marginTop: 4,
  },
  heroCompany: {
    fontSize: 14,
    color: me.ink2,
    textAlign: 'center',
    marginTop: 2,
  },
  heroRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 6,
  },
  heroBadgeCenter: {
    alignSelf: 'center',
    marginTop: 6,
  },
  heroLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 6,
  },
  viewProfileLinkWrap: {
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
});
