import { StyleSheet, Platform } from 'react-native';
import { me } from '../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg2 },
  flex: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: me.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
  },
  content: { padding: 16, paddingBottom: 32 },
  // Job card
  jobCard: {
    flexDirection: 'row',
    backgroundColor: me.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  jobIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  jobInfo: { flex: 1 },
  jobTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 4,
  },
  jobDescription: {
    fontSize: 14,
    color: me.ink2,
    lineHeight: 20,
    marginBottom: 6,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
  },
  locationText: { fontSize: 13, color: me.ink3 },
  budgetBadge: {
    alignSelf: 'flex-start',
    backgroundColor: me.brandSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  budgetText: { fontSize: 13, fontWeight: '700', color: me.brand },
  // Mode toggle
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: me.surface,
    borderRadius: 16,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
  },
  modeBtnActive: { backgroundColor: me.ink },
  modeBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink2,
  },
  modeBtnTextActive: { color: me.onBrand },
  // Form card
  formCard: {
    backgroundColor: me.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 12,
    marginTop: 4,
  },
  fieldGroup: { marginBottom: 16 },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink2,
    marginBottom: 6,
  },
  input: {
    backgroundColor: me.bg2,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: me.ink,
    borderWidth: 1,
    borderColor: me.line,
  },
  textArea: { minHeight: 120, paddingTop: 14 },
  row: { flexDirection: 'row' },
  rowSpacer: { width: 12 },
  // Currency
  currencyRow: { flexDirection: 'row', alignItems: 'stretch' },
  currencyPrefix: {
    backgroundColor: me.bg3,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  currencySymbol: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink2,
  },
  currencyInput: {
    flex: 1,
    backgroundColor: me.bg2,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 18,
    fontWeight: '600',
    color: me.ink,
    borderWidth: 1,
    borderColor: me.line,
    borderLeftWidth: 0,
  },
  // Earnings
  earningsCard: {
    backgroundColor: me.bg2,
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  earningsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  earningsLabel: { fontSize: 14, color: me.ink2 },
  earningsValue: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink,
  },
  earningsDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: me.line,
    marginVertical: 8,
  },
  earningsTotalLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: me.ink,
  },
  earningsTotalValue: {
    fontSize: 15,
    fontWeight: '700',
    color: me.brand,
  },
  // VAT toggle
  vatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    marginBottom: 8,
  },
  vatLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink2,
  },
  // Warning
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEE2E2',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  warningText: { flex: 1, fontSize: 13, color: '#DC2626', fontWeight: '500' },
  // 2026-05-28 U5: monthly bid-limit "near cap" soft notice (brand-tinted,
  // non-blocking — distinct from the red warningBanner used at the hard cap).
  bidLimitInfoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: me.brandSoft,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  bidLimitInfoText: {
    flex: 1,
    fontSize: 13,
    color: me.brand,
    fontWeight: '600',
  },
  // Char count
  charCountRow: { alignItems: 'flex-end', marginTop: 4 },
  charCount: { fontSize: 12, color: me.ink3 },
  charCountError: { color: me.errFg },
  // Error
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEE2E2',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  errorText: { flex: 1, fontSize: 13, color: '#DC2626', fontWeight: '500' },
  // Footer
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: me.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: me.ink,
    borderRadius: 28,
    paddingVertical: 16,
  },
  submitButtonDisabled: { opacity: 0.4 },
  submitButtonText: {
    color: me.onBrand,
    fontSize: 17,
    fontWeight: '600',
  },
  // Tips
  tipsCard: {
    backgroundColor: '#1A1A2E',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  tipsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  tipsTitle: { fontSize: 15, fontWeight: '700', color: '#FBBF24' },
  tipItem: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.7)',
    lineHeight: 22,
    paddingLeft: 4,
  },
});
