/**
 * English (GB) locale dictionary
 *
 * Key naming convention:
 * - namespace.key: 'common.loading', 'auth.loginButton'
 * - Use {{param}} for interpolation: 'Welcome, {{name}}'
 * - Keep keys alphabetically sorted within each namespace
 */
const enGB: Record<string, string> = {
  // Common
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.error': 'Something went wrong',
  'common.loading': 'Loading',
  'common.next': 'Next',
  'common.notFound': 'Not found',
  'common.previous': 'Previous',
  'common.save': 'Save',
  'common.search': 'Search',
  'common.submit': 'Submit',
  'common.success': 'Success',

  // Auth
  'auth.createAccount': 'Create account',
  'auth.email': 'Email address',
  'auth.forgotPassword': 'Forgot password?',
  'auth.login': 'Sign in',
  'auth.logout': 'Sign out',
  'auth.password': 'Password',
  'auth.register': 'Create your account',
  'auth.resetPassword': 'Reset password',

  // Jobs
  'jobs.bidSubmitted': 'Bid submitted successfully',
  'jobs.createJob': 'Post a job',
  'jobs.noBids': 'No bids yet',
  'jobs.status.cancelled': 'Cancelled',
  'jobs.status.completed': 'Completed',
  'jobs.status.draft': 'Draft',
  'jobs.status.inProgress': 'In progress',
  'jobs.status.open': 'Open',

  // Payments
  'payments.amount': 'Amount',
  'payments.dispute': 'Dispute payment',
  'payments.escrow': 'Funds held in escrow',
  'payments.invoice': 'Invoice',
  'payments.paid': 'Paid',
  'payments.pending': 'Payment pending',
  'payments.refunded': 'Refunded',
  'payments.vatIncluded': 'VAT included',

  // Contractor
  'contractor.available': 'Available',
  'contractor.distance': '{{distance}} miles away',
  'contractor.rating': '{{rating}} out of 5',
  'contractor.verified': 'Verified contractor',

  // Assessment
  'assessment.aiDisclaimer': 'This assessment was generated by AI and is for informational purposes only. It does not constitute a professional building survey.',
  'assessment.damageDetected': 'Damage detected',
  'assessment.noIssues': 'No issues detected',
  'assessment.severity.early': 'Early stage',
  'assessment.severity.full': 'Severe',
  'assessment.severity.midway': 'Moderate',

  // Notifications
  'notifications.empty': 'No notifications',
  'notifications.markAllRead': 'Mark all as read',
  'notifications.title': 'Notifications',

  // Errors
  'errors.authRequired': 'Please sign in to continue',
  'errors.forbidden': 'You do not have permission to access this resource',
  'errors.networkError': 'Unable to connect. Please check your internet connection.',
  'errors.notFound': 'The page you are looking for does not exist',
  'errors.serverError': 'An unexpected error occurred. Please try again.',
  'errors.sessionExpired': 'Your session has expired. Please sign in again.',
  'errors.validationFailed': 'Please check your input and try again',
};

export default enGB;
