import React from "react";

import InvoiceManagementScreen from "../../../screens/InvoiceManagementScreen";
import { CreateInvoiceScreen } from "../../../screens/create-invoice/CreateInvoiceScreen";
import { InvoiceDetailScreen } from "../../../screens/invoice-detail/InvoiceDetailScreen";
import CRMDashboardScreen from "../../../screens/CRMDashboardScreen";
import { AddClientScreen } from "../../../screens/add-client/AddClientScreen";
import { ClientDetailScreen } from "../../../screens/client-detail/ClientDetailScreen";
import FinanceDashboardScreen from "../../../screens/FinanceDashboardScreen";
import ServiceAreasScreen from "../../../screens/ServiceAreasScreen";
import QuoteBuilderScreen from "../../../screens/QuoteBuilderScreen";
import { CreateQuoteScreen } from "../../../screens/create-quote";
import { QuoteDetailScreen } from "../../../screens/quote-detail/QuoteDetailScreen";
import { QuoteTemplatesScreen } from "../../../screens/quote-templates/QuoteTemplatesScreen";
import ContractorCardEditorScreen from "../../../screens/ContractorCardEditorScreen";
import { ContractorVerificationScreen } from "../../../screens/contractor-verification/ContractorVerificationScreen";
import { CalendarScreen } from "../../../screens/CalendarScreen";
import { ReviewsScreen } from "../../../screens/ReviewsScreen";
import { ExpensesScreen } from "../../../screens/contractor/ExpensesScreen";
import { DocumentsScreen } from "../../../screens/contractor/DocumentsScreen";
import { CertificationsScreen } from "../../../screens/contractor/CertificationsScreen";
import { TimeTrackingScreen } from "../../../screens/contractor/TimeTrackingScreen";
import { AddTimeEntryScreen } from "../../../screens/contractor/AddTimeEntryScreen";
import { AddCertificationScreen } from "../../../screens/contractor/AddCertificationScreen";
import { ReportingScreen } from "../../../screens/contractor/ReportingScreen";
import { PayoutsScreen } from "../../../screens/contractor/PayoutsScreen";
import { withScreenErrorBoundary } from "../../../components/ErrorBoundaryProvider";

export const SafeInvoiceManagementScreen = withScreenErrorBoundary(InvoiceManagementScreen, "Invoice Management", { fallbackRoute: "ProfileMain" });
export const SafeCreateInvoiceScreen = withScreenErrorBoundary(CreateInvoiceScreen, "Create Invoice", { fallbackRoute: "InvoiceManagement" });
export const SafeInvoiceDetailScreen = withScreenErrorBoundary(InvoiceDetailScreen, "Invoice Detail", { fallbackRoute: "InvoiceManagement" });
export const SafeCRMDashboardScreen = withScreenErrorBoundary(CRMDashboardScreen, "CRM Dashboard", { fallbackRoute: "ProfileMain" });
export const SafeAddClientScreen = withScreenErrorBoundary(AddClientScreen, "Add Client", { fallbackRoute: "CRMDashboard" });
export const SafeClientDetailScreen = withScreenErrorBoundary(ClientDetailScreen, "Client Detail", { fallbackRoute: "CRMDashboard" });
export const SafeFinanceDashboardScreen = withScreenErrorBoundary(FinanceDashboardScreen, "Finance Dashboard", { fallbackRoute: "ProfileMain" });
export const SafeServiceAreasScreen = withScreenErrorBoundary(ServiceAreasScreen, "Service Areas", { fallbackRoute: "ProfileMain" });
export const SafeQuoteBuilderScreen = withScreenErrorBoundary(QuoteBuilderScreen, "Quote Builder", { fallbackRoute: "ProfileMain" });
export const SafeCreateQuoteScreen = withScreenErrorBoundary(CreateQuoteScreen, "Create Quote", { fallbackRoute: "QuoteBuilder" });
export const SafeQuoteDetailScreen = withScreenErrorBoundary(QuoteDetailScreen, "Quote Detail", { fallbackRoute: "QuoteBuilder" });
export const SafeQuoteTemplatesScreen = withScreenErrorBoundary(QuoteTemplatesScreen, "Quote Templates", { fallbackRoute: "QuoteBuilder" });
export const SafeContractorCardEditorScreen = withScreenErrorBoundary(ContractorCardEditorScreen, "Edit Discovery Card", { fallbackRoute: "ProfileMain" });
export const SafeContractorVerificationScreen = withScreenErrorBoundary(ContractorVerificationScreen, "Contractor Verification", { fallbackRoute: "ProfileMain" });
export const SafeCalendarScreen = withScreenErrorBoundary(CalendarScreen, "Calendar", { fallbackRoute: "ProfileMain" });
export const SafeReviewsScreen = withScreenErrorBoundary(ReviewsScreen, "Reviews", { fallbackRoute: "ProfileMain" });
export const SafeExpensesScreen = withScreenErrorBoundary(ExpensesScreen, "Expenses", { fallbackRoute: "ProfileMain" });
export const SafeDocumentsScreen = withScreenErrorBoundary(DocumentsScreen, "Documents", { fallbackRoute: "ProfileMain" });
export const SafeCertificationsScreen = withScreenErrorBoundary(CertificationsScreen, "Certifications", { fallbackRoute: "ProfileMain" });
export const SafeTimeTrackingScreen = withScreenErrorBoundary(TimeTrackingScreen, "Time Tracking", { fallbackRoute: "ProfileMain" });
export const SafeAddTimeEntryScreen = withScreenErrorBoundary(AddTimeEntryScreen, "Add Time Entry", { fallbackRoute: "TimeTracking" });
export const SafeAddCertificationScreen = withScreenErrorBoundary(AddCertificationScreen, "Add Certification", { fallbackRoute: "Certifications" });
export const SafeReportingScreen = withScreenErrorBoundary(ReportingScreen, "Reporting", { fallbackRoute: "ProfileMain" });
export const SafePayoutsScreen = withScreenErrorBoundary(PayoutsScreen, "Payouts", { fallbackRoute: "ProfileMain" });
