import { StyleSheet } from 'react-native';
import type { Ionicons } from '@expo/vector-icons';
import { me } from '../../design-system/mint-editorial';

export const CATEGORY_ICONS: Record<
  string,
  { icon: keyof typeof Ionicons.glyphMap; color: string; bg: string }
> = {
  plumbing: { icon: 'water-outline', color: '#3B82F6', bg: '#DBEAFE' },
  electrical: { icon: 'flash-outline', color: '#F59E0B', bg: '#FEF3C7' },
  roofing: { icon: 'home-outline', color: '#8B5CF6', bg: '#EDE9FE' },
  painting: { icon: 'color-palette-outline', color: '#EC4899', bg: '#FCE7F3' },
  carpentry: { icon: 'hammer-outline', color: '#92400E', bg: '#FDE68A' },
  cleaning: { icon: 'sparkles-outline', color: '#10B981', bg: '#D1FAE5' },
  general: { icon: 'construct-outline', color: '#6B7280', bg: '#F3F4F6' },
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg2 },
  content: { padding: 16 },
  headerActions: { flexDirection: 'row', gap: 12 },
  headerBtn: { padding: 2 },
  // Tabs
  tabRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
    backgroundColor: me.surface,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 6,
    borderRadius: 10,
  },
  tabActive: { backgroundColor: me.brandSoft },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink3,
  },
  tabTextActive: { color: me.brand },
  // Address
  addressCard: {
    backgroundColor: me.surface,
    borderRadius: 22,
    padding: 20,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  addressSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 12,
  },
  addressIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressLine1: {
    fontSize: 20,
    fontWeight: '700',
    color: me.ink,
    marginTop: 12,
    textAlign: 'center',
  },
  addressCity: {
    fontSize: 15,
    color: me.ink2,
    marginTop: 4,
    textAlign: 'center',
  },
  // Stats
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  statCard: {
    flex: 1,
    backgroundColor: me.surface,
    borderRadius: 20,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: me.line,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '800',
    color: me.ink,
  },
  statLabel: { fontSize: 12, color: me.ink3, marginTop: 4 },
  // Section
  section: {
    backgroundColor: me.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 12,
  },
  // Spec grid (2x2 bento)
  specGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  specTile: {
    width: '47%' as unknown as number,
    backgroundColor: me.bg2,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: me.line,
  },
  specTileIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  specTileValue: {
    fontSize: 18,
    fontWeight: '800',
    color: me.ink,
    marginBottom: 2,
  },
  specTileLabel: {
    fontSize: 12,
    color: me.ink3,
  },
  sizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
  },
  sizeText: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
  },
  // Info rows
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 12,
  },
  infoLabel: { fontSize: 15, color: me.ink2 },
  infoValue: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
  },
  notesText: {
    fontSize: 15,
    color: me.ink2,
    lineHeight: 22,
  },
  // Jobs
  jobHistoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  totalSpentBadge: {
    backgroundColor: me.brandSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  totalSpentText: {
    fontSize: 13,
    fontWeight: '700',
    color: me.brand,
  },
  emptyJobsWrap: { alignItems: 'center', paddingVertical: 20 },
  emptyJobsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  emptyJobsText: {
    fontSize: 14,
    color: me.ink3,
    textAlign: 'center',
  },
  jobCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  jobCatIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  jobRowInfo: { flex: 1, marginRight: 12 },
  jobRowTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
  },
  jobRowDate: { fontSize: 12, color: me.ink3, marginTop: 2 },
  jobRowRight: { alignItems: 'flex-end', gap: 4 },
  jobRowBudget: {
    fontSize: 15,
    fontWeight: '700',
    color: me.ink,
  },
  // Action rows
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  actionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  actionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: me.ink,
  },
});
