import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: me.bg2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: me.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
  },
  previewButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  section: {
    backgroundColor: me.surface,
    borderRadius: 16,
    padding: 20,
    marginTop: 16,
    ...me.shadow.card,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 14,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: me.ink2,
    marginBottom: 16,
    marginTop: -6,
  },
  logoUpload: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 120,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: me.line,
    borderStyle: 'dashed',
  },
  logoImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
  },
  logoPlaceholder: {
    alignItems: 'center',
  },
  cameraIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  logoPlaceholderText: {
    color: me.ink2,
    fontSize: 14,
    fontWeight: '500',
  },
  inputGroup: {
    marginBottom: 16,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink,
    marginBottom: 8,
  },
  useProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: me.brandSoft,
  },
  useProfileBtnText: {
    fontSize: 12,
    fontWeight: '500',
    color: me.brand,
  },
  textInput: {
    backgroundColor: me.bg2,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: me.ink,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  availabilityOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  availabilityOption: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: me.bg2,
  },
  availabilityOptionActive: {
    backgroundColor: me.ink,
  },
  availabilityText: {
    fontSize: 14,
    color: me.ink2,
    fontWeight: '500',
  },
  availabilityTextActive: {
    color: me.onBrand,
    fontWeight: '600',
  },
  addPortfolioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: me.line,
    borderStyle: 'dashed',
    marginBottom: 16,
    gap: 8,
  },
  addPortfolioText: {
    fontSize: 15,
    color: me.ink,
    fontWeight: '600',
  },
  portfolioGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  portfolioItem: {
    position: 'relative',
    width: '48%',
    aspectRatio: 4 / 3,
  },
  portfolioImage: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  removePortfolioButton: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveSection: {
    paddingVertical: 24,
  },
  saveButton: {
    backgroundColor: me.ink,
    borderRadius: 28,
    paddingVertical: 16,
    alignItems: 'center',
  },
  saveButtonText: {
    color: me.onBrand,
    fontSize: 16,
    fontWeight: '700',
  },
  previewContainer: {
    flex: 1,
    backgroundColor: me.bg2,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: me.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  previewTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
  },
  previewCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  cardPreview: {
    backgroundColor: me.surface,
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    ...me.shadow.pop,
  },
  previewLogo: {
    width: 80,
    height: 80,
    borderRadius: 16,
    marginBottom: 16,
  },
  previewCompanyName: {
    fontSize: 20,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 8,
  },
  previewBio: {
    fontSize: 14,
    color: me.ink2,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 20,
  },
  previewRateChip: {
    backgroundColor: me.brandSoft,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  previewRate: {
    fontSize: 18,
    fontWeight: '700',
    color: me.brand,
  },
});
