import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  jobCard: {
    backgroundColor: me.surface,
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: me.line,
  },
  heroSection: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  placeholderHero: {
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderUrgent: {
    position: 'absolute',
    bottom: 8,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: me.errFg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 3,
  },
  overlayRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  urgentTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: me.errFg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 3,
  },
  urgentTagText: {
    fontSize: 10,
    fontWeight: '800',
    color: me.onBrand,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  saveButton: {
    position: 'absolute',
    top: 10,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  statusBadge: {
    position: 'absolute',
    top: 10,
    left: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 4,
    zIndex: 5,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  cardContent: { padding: 18 },
  budgetText: {
    fontSize: 22,
    fontWeight: '800',
    color: me.ink,
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  jobTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: me.ink,
    marginBottom: 12,
    lineHeight: 22,
  },
  cardMeta: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 12,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: 13,
    color: me.ink2,
    fontWeight: '500',
  },
  tagsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
  },
  categoryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 4,
  },
  categoryTagText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  bidBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: me.warnBg,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  bidBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: me.accent,
  },
  newBadge: {
    backgroundColor: me.brandSoft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  newBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
  },
  progressSection: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  progressLabelText: {
    fontSize: 10,
    color: me.ink3,
    fontWeight: '500',
  },
  contractorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
    backgroundColor: me.bg2,
    borderRadius: 14,
    padding: 12,
  },
  contractorAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: me.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contractorInitial: {
    fontSize: 14,
    fontWeight: '700',
    color: me.brand,
  },
  contractorName: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink,
  },
  contractorRole: {
    fontSize: 12,
    color: me.ink2,
    marginTop: 1,
  },
  viewBidsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: me.ink,
    borderRadius: 16,
    paddingVertical: 14,
    marginTop: 14,
  },
  viewBidsText: {
    color: me.onBrand,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  quickBidBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: me.ink,
    borderRadius: 16,
    paddingVertical: 14,
    marginTop: 14,
  },
  quickBidText: {
    color: me.onBrand,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  quickBidAmount: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    fontWeight: '600',
  },
});
