'use client';

import React, { useState } from 'react';
import { Card } from '@/components/ui/Card.unified';
import { Icon } from '@/components/ui/Icon';
import type {
  Urgency,
  InsuranceRisk,
  RiskFactor,
  HomeownerExplanation as HomeownerExplanationType,
} from '@/lib/services/building-surveyor/types';

/**
 * AI Disclaimer Banner - Legal requirement.
 */
export function AIDisclaimerBanner() {
  return (
    <div className='rounded-lg border border-amber-300 bg-amber-50 p-4'>
      <div className='flex items-start gap-3'>
        <Icon
          name='warning'
          size={20}
          color='#D97706'
          className='mt-0.5 shrink-0'
        />
        <div className='space-y-1'>
          <div className='text-sm font-[560] text-amber-900'>
            AI-Generated Assessment — Not a Professional Survey
          </div>
          <p className='text-xs font-[460] text-amber-800 leading-relaxed'>
            This assessment was generated by artificial intelligence and is
            provided for informational purposes only. It does{' '}
            <strong>not</strong> constitute a professional building survey,
            structural engineering report, or any form of professional advice.
            It should not be relied upon for insurance claims, legal
            proceedings, or safety decisions. Always consult a qualified
            RICS-accredited surveyor or structural engineer before making
            decisions about property repairs or safety matters.
          </p>
        </div>
      </div>
    </div>
  );
}

/**
 * Urgency Badge Component
 */
export function UrgencyBadge({ urgency }: { urgency: Urgency }) {
  const urgencyConfig: Record<
    string,
    { color: string; bgColor: string; icon: string }
  > = {
    immediate: {
      color: 'text-red-700',
      bgColor: 'bg-red-100 border-red-300',
      icon: 'alert',
    },
    urgent: {
      color: 'text-emerald-700',
      bgColor: 'bg-emerald-100 border-emerald-300',
      icon: 'warning',
    },
    soon: {
      color: 'text-yellow-700',
      bgColor: 'bg-yellow-100 border-yellow-300',
      icon: 'clock',
    },
    planned: {
      color: 'text-blue-700',
      bgColor: 'bg-blue-100 border-blue-300',
      icon: 'calendar',
    },
    monitor: {
      color: 'text-gray-700',
      bgColor: 'bg-gray-100 border-gray-300',
      icon: 'eye',
    },
  };

  const config = urgencyConfig[urgency.urgency] || urgencyConfig.monitor;

  return (
    <div
      className={`rounded-lg border-2 ${config.bgColor} ${config.color} p-4`}
    >
      <div className='flex items-center gap-3'>
        <Icon name={config.icon} size={24} color='currentColor' />
        <div className='flex-1'>
          <div className='font-[640] text-lg uppercase tracking-wide'>
            {urgency.urgency}
          </div>
          <div className='text-sm font-[460] mt-1'>
            {urgency.recommendedActionTimeline}
          </div>
        </div>
      </div>
      {urgency.reasoning && (
        <div className='mt-3 text-sm font-[460] opacity-90'>
          {urgency.reasoning}
        </div>
      )}
    </div>
  );
}

/**
 * Insurance Risk Card Component
 */
export function InsuranceRiskCard({
  insuranceRisk,
}: {
  insuranceRisk: InsuranceRisk;
}) {
  const riskColor =
    insuranceRisk.riskScore >= 70
      ? 'text-red-600'
      : insuranceRisk.riskScore >= 40
        ? 'text-emerald-600'
        : 'text-green-600';

  const premiumImpactColors: Record<string, string> = {
    high: 'bg-red-100 text-red-800',
    medium: 'bg-emerald-100 text-emerald-800',
    low: 'bg-yellow-100 text-yellow-800',
    none: 'bg-green-100 text-green-800',
  };

  return (
    <Card variant='default' padding='md'>
      <div className='space-y-4'>
        <div className='flex items-start justify-between'>
          <div>
            <h3 className='text-lg font-[560] text-gray-900 mb-1'>
              Insurance Risk
            </h3>
            <div className='flex items-baseline gap-2'>
              <span className={`text-3xl font-[640] ${riskColor}`}>
                {insuranceRisk.riskScore}
              </span>
              <span className='text-sm font-[460] text-gray-600'>/100</span>
            </div>
          </div>
          <div
            className={`px-3 py-1 rounded-full text-sm font-[560] uppercase ${
              premiumImpactColors[insuranceRisk.premiumImpact] ||
              premiumImpactColors.none
            }`}
          >
            {insuranceRisk.premiumImpact} impact
          </div>
        </div>

        {insuranceRisk.riskFactors.length > 0 && (
          <div className='space-y-2 pt-2 border-t border-gray-200'>
            <div className='text-sm font-[560] text-gray-700'>
              Risk Factors:
            </div>
            {insuranceRisk.riskFactors.map(
              (factor: RiskFactor, index: number) => (
                <div key={index} className='text-sm font-[460] text-gray-600'>
                  <span className='font-[560]'>{factor.factor}:</span>{' '}
                  {factor.impact}
                </div>
              )
            )}
          </div>
        )}

        {insuranceRisk.mitigationSuggestions.length > 0 && (
          <div className='pt-2 border-t border-gray-200'>
            <div className='text-sm font-[560] text-gray-700 mb-2'>
              Mitigation Suggestions:
            </div>
            <ul className='space-y-1'>
              {insuranceRisk.mitigationSuggestions.map(
                (suggestion: string, index: number) => (
                  <li
                    key={index}
                    className='text-sm font-[460] text-gray-600 flex items-start gap-2'
                  >
                    <Icon
                      name='check'
                      size={16}
                      color='#10B981'
                      className='mt-0.5 shrink-0'
                    />
                    {suggestion}
                  </li>
                )
              )}
            </ul>
          </div>
        )}
      </div>
    </Card>
  );
}

/**
 * Homeowner Explanation Component
 */
export function HomeownerExplanationCard({
  explanation,
}: {
  explanation: HomeownerExplanationType;
}) {
  const [expanded, setExpanded] = useState(true);

  return (
    <Card variant='default' padding='md' className='bg-blue-50 border-blue-200'>
      <div className='space-y-4'>
        <div className='flex items-start justify-between'>
          <div className='flex items-center gap-3'>
            <Icon name='info' size={24} color='#3B82F6' />
            <h3 className='text-lg font-[560] text-gray-900'>For Homeowners</h3>
          </div>
          <button
            onClick={() => setExpanded(!expanded)}
            className='text-gray-500 hover:text-gray-700'
          >
            <Icon name={expanded ? 'chevronUp' : 'chevronDown'} size={20} />
          </button>
        </div>

        {expanded && (
          <div className='space-y-3'>
            <div>
              <div className='text-sm font-[560] text-gray-700 mb-1'>
                What is it?
              </div>
              <p className='text-base font-[460] text-gray-700 leading-[1.5]'>
                {explanation.whatIsIt}
              </p>
            </div>
            <div>
              <div className='text-sm font-[560] text-gray-700 mb-1'>
                Why did it happen?
              </div>
              <p className='text-base font-[460] text-gray-700 leading-[1.5]'>
                {explanation.whyItHappened}
              </p>
            </div>
            <div>
              <div className='text-sm font-[560] text-gray-700 mb-1'>
                What should I do?
              </div>
              <p className='text-base font-[460] text-gray-700 leading-[1.5]'>
                {explanation.whatToDo}
              </p>
            </div>
          </div>
        )}
      </div>
    </Card>
  );
}
