/**
 * Lazy-loaded wrapper for Advanced ML Service
 * Generated by bundle optimization script
 */

import React, { Suspense } from 'react';
import { createLazyComponent } from '../../utils/codeSplitting';
import { LoadingSpinner } from '../LoadingSpinner';

const LazyAdvancedMLService = createLazyComponent(
  () => import('../services/AdvancedMLService'),
  {
    chunkName: 'advanced-ml-service',
    timeout: 10000,
    retryAttempts: 3,
    preload: false,
  }
);

export const AdvancedMLService = (props: any) => (
  <Suspense fallback={<LoadingSpinner />}>
    <LazyAdvancedMLService {...props} />
  </Suspense>
);

export default AdvancedMLService;
