/**
 * Lazy-loaded wrapper for ML Training Pipeline
 * Generated by bundle optimization script
 */

import React, { Suspense } from 'react';
import { createLazyComponent } from '../../utils/codeSplitting';
import { LoadingSpinner } from '../LoadingSpinner';

const LazyMLTrainingPipeline = createLazyComponent(
  () => import('../services/MLTrainingPipeline'),
  {
    chunkName: 'ml-training-pipeline',
    timeout: 10000,
    retryAttempts: 3,
    preload: false,
  }
);

export const MLTrainingPipeline = (props: any) => (
  <Suspense fallback={<LoadingSpinner />}>
    <LazyMLTrainingPipeline {...props} />
  </Suspense>
);

export default MLTrainingPipeline;
