/**
 * Lazy-loaded wrapper for Video Call Service
 * Generated by bundle optimization script
 */

import React, { Suspense } from 'react';
import { createLazyComponent } from '../../utils/codeSplitting';
import { LoadingSpinner } from '../LoadingSpinner';

const LazyVideoCallService = createLazyComponent(
  () => import('../services/VideoCallService'),
  {
    chunkName: 'video-call-service',
    timeout: 10000,
    retryAttempts: 3,
    preload: false,
  }
);

export const VideoCallService = (props: any) => (
  <Suspense fallback={<LoadingSpinner />}>
    <LazyVideoCallService {...props} />
  </Suspense>
);

export default VideoCallService;
