/**
 * EmergencyJobScreen — styles split out to stay under the 300-line
 * per-file MDC limit. All colour + shadow values come from the
 * Mint Editorial token set (`me.*`), never raw hex.
 */
import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg },
  header: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: { flex: 1 },
  headline: {
    fontFamily: me.font.display,
    fontSize: 32,
    color: me.errFg,
    letterSpacing: me.displayTracking,
  },
  sub: {
    fontSize: 13,
    color: me.ink2,
    lineHeight: 18,
    marginTop: 6,
    marginBottom: 14,
  },
  honestNote: {
    flexDirection: 'row',
    gap: 10,
    padding: 12,
    backgroundColor: me.warnBg,
    borderRadius: 12,
    marginBottom: 18,
  },
  honestNoteText: {
    flex: 1,
    fontSize: 12,
    color: me.warnFg,
    lineHeight: 17,
  },
  sectionEyebrow: {
    fontSize: 11,
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    fontWeight: '700',
    marginBottom: 10,
  },
  tileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  tile: {
    width: '48.5%',
    padding: 14,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
    borderRadius: 14,
    alignItems: 'flex-start',
    gap: 8,
  },
  tileActive: { borderColor: me.errFg, borderWidth: 2 },
  tileIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileLabel: { fontSize: 13, fontWeight: '600', color: me.ink },
  propertyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
    borderRadius: 14,
    marginBottom: 18,
  },
  propertyAddress: { fontSize: 14, fontWeight: '500', color: me.ink },
  propertySub: { fontSize: 11, color: me.ink3, marginTop: 2 },
  changeLink: { fontSize: 12, fontWeight: '600', color: me.brand },
  captureRow: { flexDirection: 'row', gap: 8 },
  captureBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line,
  },
  captureBtnDone: { backgroundColor: me.brandSoft, borderColor: me.brand },
  captureBtnText: { fontSize: 13, fontWeight: '600', color: me.ink },
  preview: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 12,
    marginTop: 12,
    backgroundColor: me.bg3,
  },
  footer: {
    backgroundColor: me.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 8,
    ...me.shadow.pop,
  },
  postBtn: {
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: me.errFg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postBtnDisabled: { opacity: 0.5 },
  postBtnText: { color: me.onBrand, fontSize: 15, fontWeight: '700' },
  disclaimer: { fontSize: 11, color: me.ink3, textAlign: 'center' },
});
