import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg2 },
  flex: { flex: 1 },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: me.bg2,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: me.ink2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
    backgroundColor: me.surface,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
    textAlign: 'center',
  },
  scrollContent: { padding: 20 },
  infoBanner: {
    flexDirection: 'row',
    backgroundColor: me.brandSoft,
    borderRadius: 16,
    padding: 14,
    gap: 10,
    marginBottom: 16,
    alignItems: 'center',
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    color: me.ink,
    lineHeight: 20,
  },
  // Status banner
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 16,
  },
  statusText: { flex: 1, fontSize: 14, fontWeight: '600', lineHeight: 20 },
  // Section & field labels
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 20,
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink2,
    marginBottom: 6,
  },
  // Inputs
  input: {
    backgroundColor: me.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    color: me.ink,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: me.line,
  },
  inputError: { borderColor: me.errFg },
  textArea: { minHeight: 90, paddingTop: 12 },
  fieldError: {
    fontSize: 12,
    color: me.errFg,
    marginBottom: 10,
    marginTop: 2,
  },
  // Escrow note
  escrowNote: {
    fontSize: 13,
    color: me.brand,
    fontWeight: '500',
    marginBottom: 12,
    marginTop: 4,
  },
  // Date pickers
  dateRow: { flexDirection: 'row', gap: 12 },
  dateField: { flex: 1 },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: me.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: me.line,
  },
  dateText: { fontSize: 14, color: me.ink },
  datePlaceholder: { fontSize: 14, color: me.ink3 },
  // License type chips
  chipScroll: { marginBottom: 8, flexGrow: 0 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: me.surface,
    marginRight: 6,
    borderWidth: 1,
    borderColor: me.line,
  },
  chipActive: {
    backgroundColor: me.ink,
    borderColor: me.ink,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: me.ink2,
  },
  chipTextActive: { color: me.onBrand },
  // Agreed quote card
  agreedQuoteCard: {
    backgroundColor: '#F0FDF4',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#BBF7D0',
    marginBottom: 8,
  },
  agreedQuoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  agreedQuoteTitle: { fontSize: 15, fontWeight: '700', color: '#166534' },
  agreedQuoteSub: {
    fontSize: 13,
    color: '#15803D',
    marginBottom: 12,
    lineHeight: 18,
  },
  agreedItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#BBF7D0',
  },
  agreedItemDesc: { fontSize: 14, color: '#166534', flex: 1 },
  agreedItemTotal: { fontSize: 14, fontWeight: '700', color: '#166534' },
  agreedTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#86EFAC',
  },
  agreedTotalLabel: { fontSize: 15, fontWeight: '700', color: '#166534' },
  agreedTotalValue: {
    fontSize: 15,
    fontWeight: '800',
    color: me.brand,
  },
  // Insurance card
  insuranceCard: {
    backgroundColor: '#EFF6FF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    marginTop: 16,
    marginBottom: 4,
  },
  insuranceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  insuranceTitle: { fontSize: 15, fontWeight: '700', color: '#1E40AF' },
  insuranceSub: {
    fontSize: 13,
    color: '#3B82F6',
    marginBottom: 14,
    lineHeight: 18,
  },
  // Bottom bar
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: me.surface,
    paddingHorizontal: 20,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
    ...me.shadow.pop,
  },
  bottomRow: { flexDirection: 'row', gap: 12 },
  cancelButton: {
    flex: 0.35,
    borderRadius: 28,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderColor: me.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink2,
  },
  submitButton: {
    flex: 0.65,
    backgroundColor: me.ink,
    borderRadius: 28,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 56,
  },
  submitButtonDisabled: { opacity: 0.5 },
  submitText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
});
