import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: me.bg,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    backgroundColor: me.bg,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: me.ink2,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: me.ink,
    marginTop: 12,
  },
  emptySubtitle: {
    fontSize: 14,
    color: me.ink2,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
  },
  retryButton: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 14,
    backgroundColor: me.ink,
    borderRadius: 28,
  },
  retryButtonText: {
    color: me.onBrand,
    fontWeight: '600',
  },
  // Top nav strip — minimal back + PDF + status pill.
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
    backgroundColor: me.bg,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Spacer between back button and the right-aligned actions.
  headerSpacer: { flex: 1 },
  // Mint Editorial inline header (eyebrow + serif title), rendered
  // *inside* the scroll body so it feels like part of the document
  // rather than a chrome bar.
  screenHeader: {
    paddingHorizontal: 4,
    marginTop: 6,
    marginBottom: 20,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  headline: {
    fontFamily: me.font.display,
    fontSize: 32,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  // Retained for backwards compat with downstream readers — no longer
  // referenced by the new layout.
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
    marginLeft: 8,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
  },
  scopeCard: {
    backgroundColor: me.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: me.line,
  },
  scopeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  scopeTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  scopeItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  scopeItemBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  scopeItemInfo: { flex: 1 },
  scopeItemDesc: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink,
  },
  scopeItemQty: { fontSize: 12, color: me.ink3 },
  scopeItemTotal: {
    fontSize: 14,
    fontWeight: '700',
    color: me.ink,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  escrowBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: me.brandSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  escrowBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
  },
  amountCard: {
    backgroundColor: me.surface,
    borderRadius: 18,
    paddingVertical: 22,
    paddingHorizontal: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: me.line2,
    ...me.shadow.card,
  },
  amountLabel: {
    fontSize: 11,
    color: me.ink3,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 6,
  },
  // Serif treatment — matches the editorial direction set by the
  // Finance / Escrow / Payouts hero cards.
  amountValue: {
    fontFamily: me.font.display,
    fontSize: 36,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  draftBanner: {
    flexDirection: 'row',
    backgroundColor: me.warnBg,
    borderRadius: 16,
    padding: 14,
    gap: 10,
    marginBottom: 20,
    alignItems: 'flex-start',
  },
  draftBannerContent: {
    flex: 1,
  },
  draftBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: me.warnFg,
    marginBottom: 4,
  },
  draftBannerText: {
    fontSize: 13,
    color: me.warnFg,
    lineHeight: 18,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: me.surface,
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
    ...me.shadow.pop,
  },
  signButton: {
    backgroundColor: me.ink,
    borderRadius: 28,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 56,
  },
  signButtonDisabled: {
    opacity: 0.5,
  },
  signButtonText: {
    color: me.onBrand,
    fontSize: 16,
    fontWeight: '600',
  },
  pdfButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: me.bg2,
    marginRight: 8,
  },
  downloadPdfButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: me.line,
    backgroundColor: me.surface,
    marginBottom: 20,
  },
  downloadPdfText: {
    fontSize: 15,
    fontWeight: '500',
    color: me.ink2,
  },
});
