import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: me.bg2,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: me.ink2,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: me.line,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: me.ink,
  },
  headerSubtitle: {
    fontSize: 13,
    color: me.ink2,
    marginTop: 2,
  },
  photoCount: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink2,
  },
  content: {
    flex: 1,
  },
  sliderContainer: {
    paddingTop: 16,
  },
  timestampRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 8,
    gap: 8,
  },
  timestampBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: me.bg2,
    borderRadius: 6,
  },
  timestampText: {
    fontSize: 11,
    color: me.ink3,
    fontWeight: '500',
  },
  thumbnailRow: {
    marginTop: 12,
  },
  thumbnailContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  thumbnail: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: me.bg2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  thumbnailActive: {
    borderColor: me.ink,
    backgroundColor: me.line,
  },
  thumbnailText: {
    fontSize: 14,
    fontWeight: '700',
    color: me.ink,
  },
  instructions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 12,
    backgroundColor: me.bg2,
    borderRadius: 12,
  },
  instructionsText: {
    flex: 1,
    fontSize: 14,
    color: me.ink2,
    lineHeight: 20,
  },
  changesForm: {
    margin: 16,
    padding: 16,
    backgroundColor: me.surface,
    borderRadius: 16,
    ...me.shadow.card,
  },
  changesLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: me.ink,
    marginBottom: 12,
  },
  changesInput: {
    backgroundColor: me.bg2,
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: me.ink,
    minHeight: 100,
  },
  changesActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 12,
  },
  cancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
  },
  cancelButtonText: {
    fontSize: 15,
    color: me.ink2,
    fontWeight: '600',
  },
  submitButton: {
    backgroundColor: me.ink,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 28,
  },
  submitButtonText: {
    fontSize: 15,
    color: me.onBrand,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  actionButtons: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: me.line,
  },
  requestChangesButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: me.bg2,
  },
  requestChangesText: {
    fontSize: 15,
    fontWeight: '600',
    color: me.ink,
  },
  approveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: me.brand,
  },
  approveButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: me.onBrand,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: me.ink,
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 15,
    color: me.ink2,
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 22,
  },
});
