-- Applied migration marker for 003_payment_system.sql.
-- Canonical historical SQL is preserved in ../migrations_legacy/003_payment_system.sql.
-- The reproducible schema baseline is 20260805194939.
