-- Applied migration marker for 004_security_audit.sql.
-- Canonical historical SQL is preserved in ../migrations_legacy/004_security_audit.sql.
-- The reproducible schema baseline is 20260805194939.
