-- Applied migration marker for 006_meeting_system.sql.
-- Canonical historical SQL is preserved in ../migrations_legacy/006_meeting_system.sql.
-- The reproducible schema baseline is 20260805194939.
