-- Applied migration marker for 007_remove_social_features.sql.
-- Canonical historical SQL is preserved in ../migrations_legacy/007_remove_social_features.sql.
-- The reproducible schema baseline is 20260805194939.
