-- Applied migration marker for 008_add_location_context_tracking.sql.
-- Canonical historical SQL is preserved in ../migrations_legacy/008_add_location_context_tracking.sql.
-- The reproducible schema baseline is 20260805194939.
