-- Applied migration marker for 009_missing_core_tables.sql.
-- Canonical historical SQL is preserved in ../migrations_legacy/009_missing_core_tables.sql.
-- The reproducible schema baseline is 20260805194939.
