-- Performance optimization indexes
-- Generated by database optimization script
-- Date: 2026-01-09T23:18:18.680Z

-- Indexes for table: jobs
CREATE INDEX IF NOT EXISTS idx_jobs_id
  ON jobs (id);
-- Reason: Frequently used in WHERE clauses (93 times)

CREATE INDEX IF NOT EXISTS idx_jobs_status
  ON jobs (status);
-- Reason: Frequently used in WHERE clauses (56 times)

CREATE INDEX IF NOT EXISTS idx_jobs_contractor_id
  ON jobs (contractor_id);
-- Reason: Frequently used in WHERE clauses (50 times)

CREATE INDEX IF NOT EXISTS idx_jobs_created_at
  ON jobs (created_at);
-- Reason: Frequently used in ORDER BY (32 times)

CREATE INDEX IF NOT EXISTS idx_jobs_homeowner_id
  ON jobs (homeowner_id);
-- Reason: Frequently used in WHERE clauses (25 times)

CREATE INDEX IF NOT EXISTS idx_jobs_status
  ON jobs (status);
-- Reason: Frequently used in WHERE clauses (13 times)

CREATE INDEX IF NOT EXISTS idx_jobs_updated_at
  ON jobs (updated_at);
-- Reason: Frequently used in ORDER BY (8 times)

CREATE INDEX IF NOT EXISTS idx_jobs_user_id
  ON jobs (user_id);
-- Reason: Frequently used in WHERE clauses (7 times)

CREATE INDEX IF NOT EXISTS idx_jobs_completed_at
  ON jobs (completed_at);
-- Reason: Frequently used in ORDER BY (6 times)

CREATE INDEX IF NOT EXISTS idx_jobs_contractor_id_status
  ON jobs (contractor_id, status);
-- Reason: Fields frequently queried together (24 times)

CREATE INDEX IF NOT EXISTS idx_jobs_homeowner_id_status
  ON jobs (homeowner_id, status);
-- Reason: Fields frequently queried together (9 times)

-- Indexes for table: users
CREATE INDEX IF NOT EXISTS idx_users_id
  ON users (id);
-- Reason: Frequently used in WHERE clauses (129 times)

CREATE INDEX IF NOT EXISTS idx_users_role
  ON users (role);
-- Reason: Frequently used in WHERE clauses (50 times)

CREATE INDEX IF NOT EXISTS idx_users_contractor_id
  ON users (contractor_id);
-- Reason: Frequently used in WHERE clauses (11 times)

CREATE INDEX IF NOT EXISTS idx_users_email
  ON users (email);
-- Reason: Frequently used in WHERE clauses (9 times)

CREATE INDEX IF NOT EXISTS idx_users_created_at
  ON users (created_at);
-- Reason: Frequently used in ORDER BY (9 times)

CREATE INDEX IF NOT EXISTS idx_users_status
  ON users (status);
-- Reason: Frequently used in WHERE clauses (9 times)

CREATE INDEX IF NOT EXISTS idx_users_id
  ON users (id);
-- Reason: Frequently used in WHERE clauses (8 times)

CREATE INDEX IF NOT EXISTS idx_users_is_available
  ON users (is_available);
-- Reason: Frequently used in WHERE clauses (7 times)

CREATE INDEX IF NOT EXISTS idx_users_admin_verified
  ON users (admin_verified);
-- Reason: Frequently used in WHERE clauses (7 times)

CREATE INDEX IF NOT EXISTS idx_users_id_role
  ON users (id, role);
-- Reason: Fields frequently queried together (12 times)

CREATE INDEX IF NOT EXISTS idx_users_is_available_role
  ON users (is_available, role);
-- Reason: Fields frequently queried together (7 times)

-- Indexes for table: bids
CREATE INDEX IF NOT EXISTS idx_bids_contractor_id
  ON bids (contractor_id);
-- Reason: Frequently used in WHERE clauses (24 times)

CREATE INDEX IF NOT EXISTS idx_bids_job_id
  ON bids (job_id);
-- Reason: Frequently used in WHERE clauses (24 times)

CREATE INDEX IF NOT EXISTS idx_bids_id
  ON bids (id);
-- Reason: Frequently used in WHERE clauses (13 times)

CREATE INDEX IF NOT EXISTS idx_bids_status
  ON bids (status);
-- Reason: Frequently used in WHERE clauses (11 times)

CREATE INDEX IF NOT EXISTS idx_bids_created_at
  ON bids (created_at);
-- Reason: Frequently used in ORDER BY (9 times)

CREATE INDEX IF NOT EXISTS idx_bids_contractor_id_job_id
  ON bids (contractor_id, job_id);
-- Reason: Fields frequently queried together (6 times)

-- Indexes for table: escrow_transactions
CREATE INDEX IF NOT EXISTS idx_escrow_transactions_id
  ON escrow_transactions (id);
-- Reason: Frequently used in WHERE clauses (26 times)

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_status
  ON escrow_transactions (status);
-- Reason: Frequently used in WHERE clauses (16 times)

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_job_id
  ON escrow_transactions (job_id);
-- Reason: Frequently used in WHERE clauses (10 times)

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_payee_id
  ON escrow_transactions (payee_id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_created_at
  ON escrow_transactions (created_at);
-- Reason: Frequently used in ORDER BY (6 times)

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_job_id_status
  ON escrow_transactions (job_id, status);
-- Reason: Fields frequently queried together (7 times)

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_payee_id_status
  ON escrow_transactions (payee_id, status);
-- Reason: Fields frequently queried together (5 times)

-- Indexes for table: notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_id
  ON notifications (user_id);
-- Reason: Frequently used in WHERE clauses (10 times)

CREATE INDEX IF NOT EXISTS idx_notifications_read_user_id
  ON notifications (read, user_id);
-- Reason: Fields frequently queried together (5 times)

-- Indexes for table: building_assessments
CREATE INDEX IF NOT EXISTS idx_building_assessments_id
  ON building_assessments (id);
-- Reason: Frequently used in WHERE clauses (12 times)

CREATE INDEX IF NOT EXISTS idx_building_assessments_created_at
  ON building_assessments (created_at);
-- Reason: Frequently used in ORDER BY (10 times)

-- Indexes for table: properties
CREATE INDEX IF NOT EXISTS idx_properties_owner_id
  ON properties (owner_id);
-- Reason: Frequently used in WHERE clauses (8 times)

CREATE INDEX IF NOT EXISTS idx_properties_id
  ON properties (id);
-- Reason: Frequently used in WHERE clauses (6 times)

-- Indexes for table: job_photos_metadata
CREATE INDEX IF NOT EXISTS idx_job_photos_metadata_job_id
  ON job_photos_metadata (job_id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_job_photos_metadata_job_id_photo_type
  ON job_photos_metadata (job_id, photo_type);
-- Reason: Fields frequently queried together (5 times)

-- Indexes for table: ab_outcomes
CREATE INDEX IF NOT EXISTS idx_ab_outcomes_experiment_id
  ON ab_outcomes (experiment_id);
-- Reason: Frequently used in WHERE clauses (11 times)

-- Indexes for table: contractor_skills
CREATE INDEX IF NOT EXISTS idx_contractor_skills_contractor_id
  ON contractor_skills (contractor_id);
-- Reason: Frequently used in WHERE clauses (10 times)

-- Indexes for table: payments
CREATE INDEX IF NOT EXISTS idx_payments_status
  ON payments (status);
-- Reason: Frequently used in WHERE clauses (11 times)

CREATE INDEX IF NOT EXISTS idx_payments_created_at
  ON payments (created_at);
-- Reason: Frequently used in ORDER BY (9 times)

-- Indexes for table: messages
CREATE INDEX IF NOT EXISTS idx_messages_created_at
  ON messages (created_at);
-- Reason: Frequently used in ORDER BY (14 times)

CREATE INDEX IF NOT EXISTS idx_messages_read
  ON messages (read);
-- Reason: Frequently used in WHERE clauses (10 times)

CREATE INDEX IF NOT EXISTS idx_messages_job_id
  ON messages (job_id);
-- Reason: Frequently used in WHERE clauses (9 times)

CREATE INDEX IF NOT EXISTS idx_messages_receiver_id
  ON messages (receiver_id);
-- Reason: Frequently used in WHERE clauses (8 times)

CREATE INDEX IF NOT EXISTS idx_messages_id
  ON messages (id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_messages_read_receiver_id
  ON messages (read, receiver_id);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: contractor_quotes
CREATE INDEX IF NOT EXISTS idx_contractor_quotes_contractor_id
  ON contractor_quotes (contractor_id);
-- Reason: Frequently used in WHERE clauses (12 times)

CREATE INDEX IF NOT EXISTS idx_contractor_quotes_id
  ON contractor_quotes (id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_contractor_quotes_contractor_id_status
  ON contractor_quotes (contractor_id, status);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: reviews
CREATE INDEX IF NOT EXISTS idx_reviews_created_at
  ON reviews (created_at);
-- Reason: Frequently used in ORDER BY (11 times)

CREATE INDEX IF NOT EXISTS idx_reviews_reviewed_id
  ON reviews (reviewed_id);
-- Reason: Frequently used in WHERE clauses (11 times)

CREATE INDEX IF NOT EXISTS idx_reviews_contractor_id
  ON reviews (contractor_id);
-- Reason: Frequently used in WHERE clauses (10 times)

-- Indexes for table: job_views
CREATE INDEX IF NOT EXISTS idx_job_views_contractor_id
  ON job_views (contractor_id);
-- Reason: Frequently used in WHERE clauses (8 times)

CREATE INDEX IF NOT EXISTS idx_job_views_job_id
  ON job_views (job_id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_job_views_contractor_id_job_id
  ON job_views (contractor_id, job_id);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: contractor_posts
CREATE INDEX IF NOT EXISTS idx_contractor_posts_is_active
  ON contractor_posts (is_active);
-- Reason: Frequently used in WHERE clauses (12 times)

CREATE INDEX IF NOT EXISTS idx_contractor_posts_id
  ON contractor_posts (id);
-- Reason: Frequently used in WHERE clauses (11 times)

CREATE INDEX IF NOT EXISTS idx_contractor_posts_created_at
  ON contractor_posts (created_at);
-- Reason: Frequently used in ORDER BY (9 times)

CREATE INDEX IF NOT EXISTS idx_contractor_posts_contractor_id
  ON contractor_posts (contractor_id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_contractor_posts_contractor_id_is_active_post_type
  ON contractor_posts (contractor_id, is_active, post_type);
-- Reason: Fields frequently queried together (6 times)

CREATE INDEX IF NOT EXISTS idx_contractor_posts_id_is_active
  ON contractor_posts (id, is_active);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: agent_decisions
CREATE INDEX IF NOT EXISTS idx_agent_decisions_created_at
  ON agent_decisions (created_at);
-- Reason: Frequently used in ORDER BY (6 times)

-- Indexes for table: sso_providers
CREATE INDEX IF NOT EXISTS idx_sso_providers_contractor_id
  ON sso_providers (contractor_id);
-- Reason: Frequently used in WHERE clauses (7 times)

-- Indexes for table: contractor_schedules
CREATE INDEX IF NOT EXISTS idx_contractor_schedules_contractor_id
  ON contractor_schedules (contractor_id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_contractor_schedules_contractor_id_date
  ON contractor_schedules (contractor_id, date);
-- Reason: Fields frequently queried together (5 times)

-- Indexes for table: invoices
CREATE INDEX IF NOT EXISTS idx_invoices_contractor_id
  ON invoices (contractor_id);
-- Reason: Frequently used in WHERE clauses (7 times)

CREATE INDEX IF NOT EXISTS idx_invoices_contractor_id_status
  ON invoices (contractor_id, status);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: contractor_clients
CREATE INDEX IF NOT EXISTS idx_contractor_clients_contractor_id
  ON contractor_clients (contractor_id);
-- Reason: Frequently used in WHERE clauses (7 times)

-- Indexes for table: contractor_post_likes
CREATE INDEX IF NOT EXISTS idx_contractor_post_likes_contractor_id
  ON contractor_post_likes (contractor_id);
-- Reason: Frequently used in WHERE clauses (6 times)

CREATE INDEX IF NOT EXISTS idx_contractor_post_likes_contractor_id_post_id
  ON contractor_post_likes (contractor_id, post_id);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: dsr_requests
CREATE INDEX IF NOT EXISTS idx_dsr_requests_request_type_status_user_id
  ON dsr_requests (request_type, status, user_id);
-- Reason: Fields frequently queried together (4 times)

-- Indexes for table: contractor_follows
CREATE INDEX IF NOT EXISTS idx_contractor_follows_follower_id
  ON contractor_follows (follower_id);
-- Reason: Frequently used in WHERE clauses (6 times)

-- Indexes for table: appointments
CREATE INDEX IF NOT EXISTS idx_appointments_contractor_id_status
  ON appointments (contractor_id, status);
-- Reason: Fields frequently queried together (4 times)


-- Composite indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_jobs_status_contractor
  ON jobs (status, contractor_id)
  WHERE contractor_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_jobs_homeowner_status
  ON jobs (homeowner_id, status);

CREATE INDEX IF NOT EXISTS idx_reviews_job_rating
  ON reviews (job_id, rating);

CREATE INDEX IF NOT EXISTS idx_contractor_skills_contractor
  ON contractor_skills (contractor_id, skill_name);

-- Partial indexes for common filters
CREATE INDEX IF NOT EXISTS idx_users_contractors
  ON users (role, admin_verified, created_at DESC)
  WHERE role = 'contractor';

CREATE INDEX IF NOT EXISTS idx_jobs_active
  ON jobs (status, created_at DESC)
  WHERE status IN ('posted', 'in_progress');

-- Performance analysis views
CREATE OR REPLACE VIEW v_contractor_stats AS
SELECT
  u.id,
  u.first_name,
  u.last_name,
  COUNT(DISTINCT j.id) FILTER (WHERE j.status = 'completed') as completed_jobs,
  AVG(r.rating) as avg_rating,
  COUNT(DISTINCT r.id) as total_reviews
FROM users u
LEFT JOIN jobs j ON j.contractor_id = u.id
LEFT JOIN reviews r ON r.job_id = j.id
WHERE u.role = 'contractor'
GROUP BY u.id, u.first_name, u.last_name;

-- Add table statistics update
ANALYZE users;
ANALYZE jobs;
ANALYZE reviews;
ANALYZE contractor_skills;
