/**
 * InvoiceManagementScreen — styles split out to keep the screen file
 * under the 500-line pre-commit cap. Mint Editorial tokens only.
 */
import { StyleSheet } from 'react-native';
import { me } from '../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: me.bg },
  loadingScreen: {
    flex: 1,
    backgroundColor: me.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topNav: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenHeader: {
    paddingHorizontal: 20,
    marginTop: 6,
    marginBottom: 14,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  headline: {
    fontFamily: me.font.display,
    fontSize: 32,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  sub: {
    fontSize: 14,
    color: me.ink3,
    marginTop: 4,
  },
  filterWrap: { maxHeight: 50 },
  filterInner: {
    paddingHorizontal: 20,
    paddingVertical: 6,
    gap: 8,
    alignItems: 'center',
  },
  pill: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: me.surface,
    borderWidth: 1,
    borderColor: me.line2,
  },
  pillOn: {
    backgroundColor: me.ink,
    borderColor: me.ink,
  },
  pillText: {
    fontSize: 13,
    fontWeight: '600',
    color: me.ink2,
  },
  pillTextOn: { color: me.onBrand },
  list: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 120,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: me.surface,
    borderRadius: 14,
    marginBottom: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: me.line2,
    gap: 12,
    ...me.shadow.card,
  },
  cardIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1, gap: 4 },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  client: {
    fontSize: 15,
    fontWeight: '700',
    color: me.ink,
    flex: 1,
    marginRight: 8,
  },
  amount: {
    fontFamily: me.font.display,
    fontSize: 18,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
    gap: 8,
  },
  invNum: { fontSize: 12, color: me.ink3, flex: 1 },
  badge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 999 },
  badgeText: { fontSize: 11, fontWeight: '700' },
  actions: { flexDirection: 'row', gap: 18, marginTop: 6 },
  actBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  actText: { fontSize: 12, fontWeight: '600' },
  empty: { alignItems: 'center', paddingTop: 80, paddingHorizontal: 32 },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    fontFamily: me.font.display,
    fontSize: 22,
    color: me.ink,
    marginBottom: 6,
    letterSpacing: me.displayTracking,
  },
  emptyDesc: {
    fontSize: 13,
    color: me.ink2,
    textAlign: 'center',
    lineHeight: 19,
  },
  fab: {
    position: 'absolute',
    right: 22,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: me.brand,
    alignItems: 'center',
    justifyContent: 'center',
    ...me.shadow.pop,
  },
});
