/**
 * TimeTrackingScreen — Mint Editorial styles. Mint hero card +
 * paired bento tiles + minimal entry rows. No literal hex.
 */
import { StyleSheet } from 'react-native';
import { me } from '../../../design-system/mint-editorial';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: me.bg },
  topNav: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingBottom: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: me.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenHeader: {
    paddingHorizontal: 20,
    marginTop: 6,
    marginBottom: 16,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: me.brand,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  headline: {
    fontFamily: me.font.display,
    fontSize: 32,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  sub: {
    fontSize: 14,
    color: me.ink3,
    marginTop: 4,
  },
  // Mint hero card — the "currently tracking" deck card. We don't yet
  // have a live timer, so this surfaces this-week billable instead.
  heroCard: {
    backgroundColor: me.brand,
    borderRadius: 20,
    marginHorizontal: 20,
    paddingHorizontal: 22,
    paddingVertical: 22,
    marginBottom: 14,
  },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 6,
    textAlign: 'center',
  },
  heroBig: {
    fontFamily: me.font.display,
    fontSize: 48,
    color: me.onBrand,
    letterSpacing: me.displayTracking,
    textAlign: 'center',
    lineHeight: 56,
  },
  heroSub: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 18,
  },
  heroBtnRow: {
    flexDirection: 'row',
    gap: 10,
  },
  heroBtnSecondary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  heroBtnSecondaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: me.onBrand,
  },
  heroBtnPrimary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: me.onBrand,
  },
  heroBtnPrimaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: me.brand,
  },
  heroBtnDisabled: {
    opacity: 0.55,
  },
  // Today / This week bento.
  bentoRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 20,
    marginBottom: 22,
  },
  bentoTile: {
    flex: 1,
    backgroundColor: me.surface,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: me.line2,
    ...me.shadow.card,
  },
  bentoLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: me.ink3,
    marginBottom: 4,
  },
  bentoValue: {
    fontFamily: me.font.display,
    fontSize: 22,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  sectionEyebrow: {
    paddingHorizontal: 20,
    marginBottom: 12,
    fontSize: 11,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  loadingWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: { fontSize: 13, color: me.ink2 },
  emptyState: { alignItems: 'center', paddingTop: 36, paddingHorizontal: 40 },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: me.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyTitle: {
    fontFamily: me.font.display,
    fontSize: 20,
    color: me.ink,
    marginBottom: 4,
    letterSpacing: me.displayTracking,
  },
  emptySubtitle: {
    fontSize: 13,
    color: me.ink2,
    textAlign: 'center',
    lineHeight: 19,
  },
  retryText: {
    fontSize: 13,
    color: me.brand,
    fontWeight: '700',
    marginTop: 8,
  },
  list: { paddingHorizontal: 20, paddingBottom: 100 },
  sectionHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: me.ink3,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginTop: 14,
    marginBottom: 8,
  },
  entryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: me.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: me.line2,
    gap: 12,
    ...me.shadow.card,
  },
  entryInfo: { flex: 1, gap: 2 },
  entryTask: {
    fontSize: 14,
    fontWeight: '600',
    color: me.ink,
  },
  entryBillable: { fontSize: 11, color: me.brand, fontWeight: '600' },
  entryNonBillable: { fontSize: 11, color: me.ink3 },
  entryHours: {
    fontFamily: me.font.display,
    fontSize: 18,
    color: me.ink,
    letterSpacing: me.displayTracking,
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: me.brand,
    justifyContent: 'center',
    alignItems: 'center',
    ...me.shadow.pop,
  },
});
