const fs=require('fs');
const path=require('path');
const report='audit/2026-09-06/READINESS-AUDIT.md';
let s=fs.readFileSync(report,'utf8');
s=s.replace('# Mintenance production-readiness audit — 6 September 2026','# Mintenance production-readiness audit — completed 7 September 2026');
s=s.replace('Local diagnostic results are in `database-diagnostics.log`, `baseline-grants.log` and `diagnostic-tests.log`.','Diagnostic evidence includes `fresh-database-diagnostics.log`, `local-http-diagnostics.json`, `diagnostic-tests.log`, `storage-diagnostics.log` and the integration-test logs. Fresh-schema and real HTTP results supersede earlier environment limitations below.');
s=s.replace('| Selected payment/webhook Vitest suites |','| Complete web Vitest suite | 284 files, 3,119 tests passed | Includes the initial six audit diagnostics; mocks still apply; not additive to selected suite counts |\n| Fresh-stack integration suite | 9 suites passed, 1 suite failed during fixture setup; 62 tests passed, 4 skipped | Real Supabase Auth/REST/database; no Stripe transactions |\n| Audit copy of cross-user suite | 4 tests passed | Valid separate messaging fixture and returned-row assertions; original suite unchanged |\n| Added storage diagnostic | 1 test passed | Confirms unsafe schema/helper behavior; supplemented by real HTTP reproduction |\n| Selected payment/webhook Vitest suites |');
s=s.replace('The full repository suite/lint, native builds and device tests were not run.','The complete web suite was subsequently run; full-web lint results are recorded in the completion appendix. Native builds, full mobile tests and device tests were not run.');
s=s.replace(/Only local PostgreSQL was available[\s\S]*?baseline's grant\/revoke pattern\./,'The original local stack initially provided only PostgreSQL and was behind current migrations. To remove that limitation, a disposable stack named `mintenance-audit-20260906` was created with separate ports (API 55321, database 55322), copied current migrations and seed execution disabled. All current migrations applied successfully. Auth, REST and Storage became available. The rollback SQL diagnostics reproduced F1, F2, F6 and F7 against this fresh schema; real authenticated REST reproduced self-admin escalation. The existing database was not reset or migrated. Deployed infrastructure remains outside the tested scope.');
s=s.replace('Browser login used synthetic input and could not authenticate.','Initial browser login used synthetic input without a configured auth service. Subsequent real HTTP requests successfully logged synthetic accounts into the web application against disposable local Auth, and verified logout.');
s=s.replace('Only public authentication/navigation screens were exercised in-browser.','Only public authentication/navigation screens were exercised in-browser; authenticated property mutation/read and cookie login/logout were subsequently exercised through the real web HTTP pipeline.');
s=s.replace('Effective function privileges also permit anon/authenticated execution','Fresh-schema SQL and real REST both reproduced this escalation. Effective function privileges also permit anon/authenticated execution');
s=s.replace('### F8 — High, high confidence about token mismatch; end-to-end mobile login blocked: proxy verifies mobile tokens with the cookie verifier','### F8 — High, confirmed with a real Supabase token: proxy verifies mobile tokens with the cookie verifier');
s=s.replace(/\*\*Evidence\/impact:\*\* An otherwise valid synthetic ES256 token[\s\S]*?runs\./,'**Evidence/impact:** A real access token obtained by signing a synthetic account into the fresh local Supabase Auth service received HTTP 401 `Invalid token` from the unchanged web proxy at `/api/properties`. The same account successfully authenticated via the web cookie login endpoint. The earlier ES256 helper diagnostic additionally demonstrates algorithm incompatibility. Protected mobile API requests fail before the route verifier; native UI behavior remains untested.');
const additions=`### F13 — High, confirmed end-to-end: property photo re-signing grants access to another owner's private object

**Location:** \`apps/web/lib/api/job-storage.ts:29\` (one-year default), \`:81\` (\`extractJobStoragePath\`), \`:113\` (\`resignJobStorageUrls\`); \`apps/web/lib/validation/schemas-user.ts:338\`; \`apps/web/app/api/properties/[id]/route.ts:62\` (GET) and \`:197\` (PUT).

**Journey/preconditions:** A logged-in homeowner can edit their own property's photos and knows another private object's key, for example from an expired or previously shared URL. No administrator role or access to the other property is required. Random object keys are not assumed enumerable.

**Expected/actual:** Access to one's own property should not authorize signing another property's object. The schema accepts any URL, the writer stores it unchanged, and the reader extracts a Job-storage key without checking URL origin or object ownership. Its privileged signer then issues a fresh bearer URL, by default valid for a year.

**Reproduction:** Uploaded a valid synthetic PNG under owner A's private key. Owner B's direct Storage download was denied. B logged into the web application and PUT an unrelated-origin URL containing A's key into B's own property's photos. On a normal cold worker, GET of B's property returned a signed URL that downloaded A's exact PNG bytes. PUT and GET both returned 200. All accounts, objects and properties were synthetic; the report contains no signed URLs. The warm-worker attempt initially failed because of F14, which is not a dependable safeguard.

**Impact:** Previously known or expired private-image references can be turned into renewed access without the owner's permission, defeating property/photo isolation and revocation expectations.

**Smallest fix:** Store owned object references instead of trusting arbitrary URL paths. At write and signing time, verify bucket/key association with an authorized property/job/upload; validate exact configured origin for legacy URL conversion. Shorten bearer URL lifetime and enforce access again on renewal. Origin validation alone does not repair same-origin cross-owner keys.

**Acceptance:** A legitimate owner can upload/view their own image. Another owner cannot attach, re-sign or fetch its key, including an expired same-origin URL, an unrelated-origin URL with the same path and a bare key. Repeat on warm and cold workers; direct Storage and web API decisions must agree.

### F14 — High, confirmed SDK/runtime behavior: login changes the identity of the shared privileged client

**Location:** \`apps/web/lib/auth-manager.ts:84\` (\`AuthManager.login\`) and \`:236\` (registration); \`apps/web/lib/api/supabaseServer.ts:150\` (lazy singleton and proxy); shared options disable persistence but do not prevent in-memory sessions.

**Journey/preconditions:** A worker uses the shared \`serverSupabase\` instance for user login and subsequently for privileged database/storage work. The SDK retains the user session in memory even with \`persistSession:false\`.

**Expected/actual:** A service client should retain its fixed service identity; each login should use a separate auth client. With identical SDK options and the actual local provider, the same service client could read another user's property before sign-in and returned zero rows after signing in as the unrelated account. The real warm web worker could not sign the other owner's object after login; the cold worker could, proving identity-dependent operation in the application path.

**Impact:** Server operations can unexpectedly run under the most recently signed-in user's RLS identity. This causes intermittent failures and unreliable privileged operations across requests; it is not proof that every request discloses the last user's records. It also complicates verification of every service-role fallback. Registration uses the same shared client and should be isolated too.

**Smallest fix:** Use a fresh anon/auth client for sign-in/sign-up/password operations. Keep the service client immutable and dedicated to server-authorized operations. Do not solve this with a shared sign-out after login, which introduces another cross-request race.

**Acceptance:** Interleave two users' logins with privileged operations and assert the service client's request identity never changes; session state is isolated. Run warm-worker, cold-worker and concurrent request tests against real Supabase.

### F15 — Medium, confirmed: isolation tests can mistake missing counts for denied writes

**Location:** \`apps/web/__tests__/integration-real/cross-user-isolation.integration.test.ts:103\` (invalid message fixture), \`:203\`, \`:305\` and \`:308\` (mutation assertions); installed \`node_modules/@supabase/postgrest-js/src/PostgrestTransformBuilder.ts:26\` (actual SDK contract).

**Scenario/impact:** The original suite fails in setup because a message targets an unassigned contractor. After correcting that in an audit-only copy, its positive assigned-contractor write assertion fails: mutation \`.select()\` accepts only columns, not the supplied \`{count,head}\` options. Thus \`count\` remains null. Denial assertions using \`(count ?? 0)\` can pass without establishing that a write affected zero rows. This weakens test evidence, not the database's actual authorization rules.

**Fix/acceptance:** Give messaging and unassigned-discovery separate valid fixtures. Assert actual returned mutation rows and verify persisted values where appropriate, or request supported counts at the mutation builder. In the audit copy, these corrections preserved the intended access expectations and all four tests passed. Original tests were preserved; the initial suite failure remains recorded.

`;
s=s.replace('### Architectural/operational risks requiring verification',additions+'### Architectural/operational risks requiring verification');
s=s.replace(/1\. \*\*Reconciliation query correctness and coverage:[\s\S]*?especially consequential while F4\/F6\/F9 exist\./i,'1. **Reconciliation backlog coverage:** `apps/web/lib/services/payment/PaymentReconciliationService.ts:67` processes only the newest 100 rows, without a persisted cursor or pagination in this method. Verify eventual coverage of older mismatches. The earlier suspicion about `.neq(column, null)` is withdrawn: actual PostgREST testing on a nullable text column returned the same expected non-null row as `.not(column, \'is\', null)`. It must not be cited as a confirmed defect.');
s=s.replace('2. **Schema drift:** Local migrations and effective schema differ. No assurance is possible about a deployment\'s ACLs, triggers or new credit/dispute RPCs until migration application and effective-state tests run on a disposable fresh and upgraded database.','2. **Deployment/upgrade parity:** Current migrations applied successfully to the disposable fresh stack and the critical flaws reproduced there. The original database remains behind. Validate a representative upgrade path and the eventual deployed effective ACLs/triggers; fresh-stack success alone does not establish deployment parity.');
s=s.replace('| Login/logout/reset/session expiry/MFA | Partially verified | Public login/reset navigation, unsuccessful synthetic login and auth tests; successful login, email, revocation and MFA not exercised |','| Login/logout/reset/session expiry/MFA | Partially verified | Real web cookie login/logout passed; protected request after logout returned 401. Public reset navigation and auth tests passed; email/reset completion, expired sessions and MFA interaction remain unverified. F14 affects shared identity. |');
s=s.replace('| Property create/edit/photos/documents/sharing | Partially verified | Owner/unrelated RLS checks before escalation passed; full shared-role and storage tests blocked; F1 undermines isolation |','| Property create/edit/photos/documents/sharing | Confirmed failing | Real own-property PUT/GET worked, but F13 returned another owner\'s private PNG. Direct Storage correctly denied that download. Sharing-role/document lifecycle remains partial. |');
s=s.replace('| Messaging/attachments/unread | Partially verified | Participant/pagination/read tracking inspected; upload/realtime/offline behavior unavailable |','| Messaging/attachments/unread | Partially verified | Real cross-user message/document read/write/delete isolation passed in the corrected diagnostic suite. Chat UI, realtime, unread synchronization and offline behavior remain unverified. |');
s=s.replace('| Mobile protected API journeys | Confirmed failing at token-class boundary | Helper diagnostic plus proxy trace; real device/session configuration remains unverified |','| Mobile protected API journeys | Confirmed failing | Real local Supabase access token was rejected by the web proxy with 401; cookie login for the same account succeeded. Device UI and handoffs remain unverified. |');
s=s.replace('1. **Repair and verify effective database authority (F1, F2).**','1. **Repair and verify database, object-signing and client authority (F1, F2, F13, F14).**');
s=s.replace('Add storage policies/content/size/signed-URL tests and sharing-role tests.','Add storage policies/content/size/signed-URL tests and sharing-role tests; repair original integration evidence defects (F15).');
s=s.replace('No production configuration, application route or service was edited.','No production configuration, application route or service was edited. Additional audit-only files include `apps/web/__tests__/audit/readiness-storage-diagnostics.test.ts`, `apps/web/__tests__/integration-real/readiness-audit-cross-user.integration.test.ts`, local HTTP diagnostics, launchers and completion logs. The cross-user copy is an isolated diagnostic correction, not a modification of the original suite.');
s+='\n## Completion evidence and remaining release gates\n\nThe audit work available on this host is complete; remediation is not part of this audit. The fresh local environment closed the original database/Auth/REST/Storage access gap. The remaining release gates are real Stripe test-mode challenges/transfers/refunds and webhook delivery, email/reset/MFA end-to-end behavior, native mobile/device handoffs, authenticated browser journey coverage, AI evaluation and realistic load/recovery measurements. These were not substituted with mocked success. No complete money-moving journey is marked verified.\n\nThe original 62 passing integration tests include database state/RLS exercises for bids, escrow, payments, contract/review records, signup-trigger behavior, and compliance/notifications. They do not exercise Stripe: the `payment-flow` title refers to local payment rows. Admin-created confirmed fixtures bypass email verification. The corrected four-test copy adds meaningful property/job/message/document/report isolation but does not establish immutable profile roles (F1 tests that separately).\n\n';
s=s.replace(/`((?:apps|packages|supabase|node_modules)\/[^`]+)`/g,(whole,ref)=>{const p=ref.replace(/:\d+$/,'');if(!fs.existsSync(p))return whole;return '['+ref+'](<'+path.resolve(p).replace(/\\/g,'/')+(ref.match(/:\d+$/)?.[0]||'')+'>)';});
fs.writeFileSync(report,s);
console.log('Report updated with fresh-schema, HTTP, storage, test-quality and corrected reconciliation evidence.');
