name: Dependency Security Updates

on:
  schedule:
    # Run weekly on Sundays at 1 AM UTC
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for outdated packages
      run: |
        npm outdated --json > outdated.json || true
        if [ -s outdated.json ]; then
          echo "Outdated packages found:"
          cat outdated.json
        else
          echo "No outdated packages found"
        fi

    - name: Run security audit
      run: npm audit --audit-level moderate

    - name: Update dependencies
      run: |
        npm update
        npm audit fix --force || true

    - name: Run tests
      run: npm test

    - name: Create security update PR
      if: github.event_name == 'schedule'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Security: Update dependencies'
        title: 'Security: Automated dependency updates'
        body: |
          This PR contains automated security updates for dependencies.
          
          ## Changes
          - Updated outdated packages
          - Applied security fixes
          - Ran security audit
          
          ## Review Required
          Please review the changes and test thoroughly before merging.
        branch: security/update-dependencies-${{ github.run_number }}
        delete-branch: true
