name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check:web

      - name: Lint
        run: npm run lint:web

      - name: Build
        run: npm run build:web
        env:
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Build Success Summary
        if: success()
        run: |
          echo "# ✅ Build Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The web application has been built successfully and is ready for deployment." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "- Vercel will automatically deploy this build" >> $GITHUB_STEP_SUMMARY
          echo "- Check the Vercel dashboard for deployment URL" >> $GITHUB_STEP_SUMMARY

      # NOTE: Uncomment when Vercel secrets are configured
      # - name: Deploy to Vercel (Production)
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     npm install -g vercel
      #     cd apps/web
      #     vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #
      # - name: Deploy to Vercel (Preview)
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     npm install -g vercel
      #     cd apps/web
      #     vercel --token=${{ secrets.VERCEL_TOKEN }}
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
