name: Performance Budget Checks

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  performance-budget:
    name: Performance Budget Enforcement
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type check
        run: npm run type-check
        
      - name: Run performance budget checks
        run: npm run performance:check
        
      - name: Bundle size analysis
        run: npm run bundle:analyze
        
      - name: Check bundle size limits
        run: node scripts/check-bundle-size.js
        
      - name: Memory usage check
        run: node scripts/check-memory-usage.js
        
      - name: Performance report
        run: npm run performance:report
        
      - name: Comment PR with performance results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            let reportContent = '';
            
            // Read performance report if exists
            if (fs.existsSync('performance-report.md')) {
              reportContent = fs.readFileSync('performance-report.md', 'utf8');
            } else {
              reportContent = '## Performance Budget Report\n\nNo performance issues detected. ✅';
            }
            
            // Comment on PR
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reportContent
            });
            
      - name: Fail if performance budget exceeded
        run: |
          if [ -f "performance-violations.txt" ]; then
            echo "❌ Performance budget violations detected!"
            cat performance-violations.txt
            exit 1
          fi
          echo "✅ All performance budgets passed!"

  lighthouse-ci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for web
        run: npm run build:web
        
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Analyze bundle
        run: |
          npm run bundle:export
          npm run bundle:analyze
          
      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: |
            bundle-analysis-report.json
            metro-bundle-report.html
          retention-days: 30