name: Style Lint (No Hex Colors)

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  no-hex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run hex color style check
        run: node scripts/ci/check-no-hex.js

